const readinessGates=["regulated_entity","product_policy","decision_bundle","accounting_profile","compliance_profile","provider_certification","document_pack","customer_content","operations_runbook","support_model","tenant_uat","reconciliation","rollback_plan"];
const ui=Object.fromEntries(["home","brand-mark","brand-name","banker-link","refresh","summary","status","product-list","detail-title","detail-content","approval-list","brand-list","configuration-template"].map(id=>[id.replaceAll("-","_"),document.querySelector(`#${id}`)]));
const tenantId=decodeURIComponent(location.pathname.match(/^\/t\/([^/]+)/)?.[1]??"");
const basePath=`/t/${encodeURIComponent(tenantId)}`;
let workspace,brands,selectedType;
ui.home.href=`${basePath}/`;ui.banker_link.href=`${basePath}/staff/`;ui.refresh.addEventListener("click",load);void load();

async function load(){state("Loading governed product state…");try{[workspace,brands]=await Promise.all([request("/admin/product-platform"),request("/admin/brand-governance")]);await brand();render();state("")}catch(error){state(error.message,true)}}
async function brand(){try{const {experience}=await request(`${basePath}/brand-experience?channel=administration&locale=en`);const name=experience.theme?.brandName||experience.legalIdentity?.regulatedEntityName;ui.brand_name.textContent=`${name} · Administration`;ui.brand_mark.textContent=name?.slice(0,1)||"";applyTheme(experience.theme)}catch{ui.brand_name.textContent="Brand configuration required · Administration"}}
function render(){const active=workspace.products.filter(p=>p.status==="active").length;const ready=workspace.products.filter(p=>p.readiness?.complete).length;ui.summary.replaceChildren(metric(`${workspace.canonicalJourneyCount} canonical journeys`),metric(`${workspace.products.length} subscribed`),metric(`${active} active`),metric(`${ready} ready`),metric(`${workspace.pendingTransitions.length} pending approvals`));renderProducts();renderApprovals();renderBrands();if(selectedType)renderDetail(selectedType)}
function renderProducts(){ui.product_list.replaceChildren();for(const contract of [...workspace.contracts].sort((a,b)=>name(a.journeyType).localeCompare(name(b.journeyType)))){const product=productFor(contract.journeyType);const button=element("button","product-row");button.type="button";button.setAttribute("aria-current",String(selectedType===contract.journeyType));button.append(element("strong","",name(contract.journeyType)),element("small","",product?`${product.status} · configuration v${product.configurationVersion}`:"Not subscribed"));button.addEventListener("click",()=>{selectedType=contract.journeyType;renderProducts();renderDetail(selectedType)});ui.product_list.append(button)}}
function renderDetail(type){const contract=workspace.contracts.find(item=>item.journeyType===type),product=productFor(type);ui.detail_title.textContent=name(type);ui.detail_content.replaceChildren();const head=element("div","detail-head"),copy=element("div");copy.append(element("p","",`${contract.facility.type.replaceAll("_"," ")} · ${contract.security.type.replaceAll("_"," ")} · contract v${contract.contractVersion}`));const actions=element("div","form-actions");if(!product)actions.append(action("Subscribe",()=>subscribe(contract)));else{actions.append(action("Configure",()=>configuration(contract,product)));if(product.status==="configured")actions.append(action("Approve configuration",()=>approveConfiguration(product)));if(product.status==="approved")actions.append(action("Propose activation",()=>proposeTransition(product,"activation")));if(product.status==="active")actions.append(action("Propose suspension",()=>proposeTransition(product,"suspension"),"danger"));if(["approved","active","suspended"].includes(product.status))actions.append(action("Propose retirement",()=>proposeTransition(product,"retirement"),"danger"))}head.append(copy,actions);ui.detail_content.append(head,contractSection("Required facts",contract.requiredFacts),contractSection("Required evidence",contract.requiredEvidence),contractSection("Lifecycle capabilities",contract.lifecycleCapabilities));if(product)ui.detail_content.append(readiness(product))}
function contractSection(title,items){const card=element("section","contract-card"),list=element("div","pill-list");for(const item of items)list.append(element("span","pill",item.replaceAll("_"," ")));card.append(element("h3","",title),list);return card}
function readiness(product){const wrap=element("section","contract-card"),list=element("div","readiness-grid");wrap.append(element("h3","",product.readiness.complete?"Readiness complete":"Readiness blockers"));for(const gap of product.readiness.gaps)list.append(element("span","gap",gap));if(!product.readiness.gaps.length)list.append(element("span","","All configured readiness gates are present."));wrap.append(list);return wrap}
async function subscribe(contract){const template=workspace.templates.find(item=>item.productType===contract.journeyType);if(!template)return state("No published platform template exists for this journey. Platform administration must publish it first.",true);const subscriptionRef=prompt("Governed subscription reference");if(!subscriptionRef)return;await mutate(`/admin/product-platform/products/${contract.journeyType}/subscription`,{commandId:crypto.randomUUID(),templateVersion:template.version,subscriptionRef})}
function configuration(contract,product){const fragment=ui.configuration_template.content.cloneNode(true),form=fragment.querySelector("form"),evidence=form.querySelector("#readiness-fields");for(const gate of readinessGates){const label=element("label","",gate.replaceAll("_"," ")),input=document.createElement("input");input.name=`readiness_${gate}`;input.required=true;label.append(input);evidence.append(label)}form.querySelector("[data-close]").addEventListener("click",()=>renderDetail(contract.journeyType));form.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(form),csv=key=>(data.get(key)||"").split(",").map(x=>x.trim()).filter(Boolean),readinessEvidence=Object.fromEntries(readinessGates.map(gate=>[gate,data.get(`readiness_${gate}`)]));const payload={commandId:crypto.randomUUID(),configuration:{regulatedEntityRefs:csv("regulatedEntityRefs"),channels:data.getAll("channels"),productPolicyRef:data.get("productPolicyRef"),decisionBundleRef:data.get("decisionBundleRef"),accountingProfileRef:data.get("accountingProfileRef"),complianceProfileRef:data.get("complianceProfileRef"),providerProfileRefs:csv("providerProfileRefs"),documentPackRef:data.get("documentPackRef"),staffingGrants:[{grantId:data.get("grantId"),principalId:data.get("principalId"),roles:csv("roles"),scopeRefs:csv("scopeRefs"),evidenceRef:data.get("staffingEvidenceRef")}],programmeRefs:csv("programmeRefs"),whiteLabelBinding:{brandVersionRef:data.get("brandVersionRef"),legalEntityDisclosureRef:data.get("legalEntityDisclosureRef"),localeRefs:csv("localeRefs"),communicationTemplateSetRef:data.get("communicationTemplateSetRef"),documentTemplateSetRef:data.get("documentTemplateSetRef")},readinessEvidence,effectiveFrom:new Date(data.get("effectiveFrom")).toISOString(),effectiveTo:data.get("effectiveTo")?new Date(data.get("effectiveTo")).toISOString():null}};await mutate(`/admin/product-platform/products/${contract.journeyType}/configuration`,payload)});ui.detail_content.replaceChildren(fragment)}
async function approveConfiguration(product){const approvalRef=prompt("Independent approval reference");if(approvalRef)await mutate(`/admin/product-platform/products/${product.productType}/approval`,{commandId:crypto.randomUUID(),approvalRef})}
async function proposeTransition(product,target){const requestId=crypto.randomUUID(),payload={requestId};if(target==="activation")payload.activationRef=prompt("Activation evidence reference");else payload.reason=prompt(`Reason for ${target}`);if(target==="activation"&&!payload.activationRef||target!=="activation"&&!payload.reason)return;await mutate(`/admin/product-platform/products/${product.productType}/${target}-proposal`,payload)}
function renderApprovals(){ui.approval_list.replaceChildren();if(!workspace.pendingTransitions.length)return ui.approval_list.append(element("p","empty","No product transitions await independent approval."));for(const request of workspace.pendingTransitions){const row=element("article","approval-row"),copy=element("div");copy.append(element("strong","",`${name(request.productType)} · ${request.target}`),element("small","",`Proposed by ${request.proposedBy} · ${request.requestId}`));const button=action("Approve",async()=>{const approvalRef=prompt("Independent approval reference");if(!approvalRef)return;await mutate(`/admin/product-platform/products/${request.productType}/${request.target}`,{commandId:crypto.randomUUID(),approvalRef})});row.append(copy,button);ui.approval_list.append(row)}}
function renderBrands(){ui.brand_list.replaceChildren();const releases=brands.workspace.releases;if(!releases.length)return ui.brand_list.append(element("p","empty","No governed brand release has been published. Product activation remains blocked."));for(const release of releases){const row=element("article","brand-row");row.append(element("strong","",`${release.scope.level.replaceAll("_"," ")} · v${release.version}`),element("p","",`${release.status} · ${release.applicableJourneyTypes.length} journeys · ${release.defaultLocale}`));ui.brand_list.append(row)}}
async function mutate(url,body){state("Saving governed change…");try{await request(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await load()}catch(error){state(error.message,true)}}
function productFor(type){return workspace.products.find(item=>item.productType===type)}function action(label,handler,className=""){const button=element("button",className,label);button.type="button";button.addEventListener("click",handler);return button}function metric(text){return element("span","metric",text)}function name(value){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}function element(tag,className="",text=""){const node=document.createElement(tag);if(className)node.className=className;if(text)node.textContent=text;return node}function state(message,error=false){ui.status.textContent=message;ui.status.classList.toggle("error",error)}async function request(url,options={}){const response=await fetch(url,{...options,credentials:"same-origin",cache:"no-store",headers:{accept:"application/json",...(options.headers??{})}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message??`Request failed (${response.status})`);return body}function applyTheme(theme={}){for(const [key,variable] of Object.entries({primaryColor:"--admin-primary",secondaryColor:"--admin-accent",surfaceColor:"--admin-surface",textColor:"--admin-text"})){const value=theme[key];if(/^#[0-9a-f]{6}$/i.test(value??""))document.documentElement.style.setProperty(variable,value)}}
