const ui={catalogue:document.querySelector("#catalogue"),workspace:document.querySelector("#workspace"),status:document.querySelector("#status"),form:document.querySelector("#journey-form"),sections:document.querySelector("#form-sections"),documents:document.querySelector("#document-list"),actions:document.querySelector("#action-list"),title:document.querySelector("#workspace-title"),meta:document.querySelector("#schema-meta"),language:document.querySelector("#language"),staffChannel:document.querySelector("#staff-channel"),staffChannelLabel:document.querySelector("#staff-channel-label"),offline:document.querySelector("#offline"),formStatus:document.querySelector("#form-status"),back:document.querySelector("#back")};
const path=location.pathname;
const tenantId=decodeURIComponent(path.match(/^\/t\/([^/]+)/)?.[1]??"");
const surface=path.includes("/portal/")?"borrower":path.includes("/partners/")?"partner":path.includes("/field/")?"field":"staff";
let channel=surface==="staff"?new URLSearchParams(location.search).get("channel")??"credit":surface;
let catalogue=null,current=null;

if(surface!=="staff"){ui.staffChannel.hidden=true;ui.staffChannelLabel.hidden=true}else ui.staffChannel.value=channel;
ui.back.href=`/t/${encodeURIComponent(tenantId)}/${surface==="borrower"?"portal":surface==="partner"?"partners":surface==="field"?"field":"staff"}/`;
ui.staffChannel.addEventListener("change",()=>{channel=ui.staffChannel.value;loadCatalogue()});
ui.language.addEventListener("change",()=>{document.documentElement.lang=ui.language.value;renderCatalogue();if(current)renderSchema(current)});
document.querySelector("#close-workspace").addEventListener("click",()=>{ui.workspace.hidden=true;ui.catalogue.hidden=false;ui.catalogue.focus()});
document.querySelector("#save-draft").addEventListener("click",()=>save(false));
ui.form.addEventListener("submit",event=>{event.preventDefault();if(!ui.form.reportValidity())return;save(true)});
addEventListener("online",networkState);addEventListener("offline",networkState);networkState();loadCatalogue();

async function loadCatalogue(){current=null;ui.workspace.hidden=true;ui.catalogue.hidden=false;state("Loading authorised journeys…");try{const response=await api(`/journey-workspaces/${channel}/catalogue`);catalogue=response.catalogue;renderCatalogue();state(catalogue.journeyCount?`${catalogue.journeyCount} authorised product journeys across ${catalogue.schemaCount} workspace shapes.`:"No product journeys are active for this tenant. Ask an authorised administrator to complete subscription and activation.")}catch(error){state(error.message,true)}}
function renderCatalogue(){ui.catalogue.replaceChildren();if(!catalogue)return;const lang=ui.language.value;for(const item of catalogue.journeys){const card=node("article","journey-card"),kind=node("p","eyebrow",item.archetype.replaceAll("_"," ")),title=node("h2","",label(item.title,lang)),copy=node("p","",`${item.sections.reduce((n,section)=>n+section.fields.length,0)} authorised fields · ${item.documents.length} evidence types`),button=node("button","","Open journey");button.type="button";button.addEventListener("click",()=>openJourney(item.journeyType));card.append(kind,title,copy,button);ui.catalogue.append(card)}}
async function openJourney(journeyType){state("Loading governed schema…");try{const response=await api(`/journey-workspaces/${channel}/schemas/${encodeURIComponent(journeyType)}`);current=response.schema;renderSchema(current);ui.catalogue.hidden=true;ui.workspace.hidden=false;ui.title.focus();state("");activity("workspace_opened",journeyType)}catch(error){state(error.message,true)}}
function renderSchema(schema){const lang=ui.language.value;ui.title.textContent=label(schema.title,lang);ui.title.tabIndex=-1;ui.meta.textContent=`${schema.journeyType.replaceAll("_"," ")} · schema v${schema.schemaVersion} · ${schema.channel}`;ui.sections.replaceChildren();for(const section of schema.sections){const wrap=node("section","form-section"),heading=node("h3","",label(section.title,lang)),grid=node("div","field-grid");for(const item of section.fields){const field=node("label","field"),caption=node("span","",label(item.label,lang));if(item.required)caption.append(node("span","required"," *"));const input=document.createElement("input");input.name=item.fieldId;input.id=`field-${item.fieldId}`;input.required=item.required;input.autocomplete=item.autocomplete??"off";input.inputMode=["money_string","decimal_string","integer"].includes(item.type)?"decimal":item.type==="tel"?"tel":"text";input.type=item.type==="date"?"date":item.type==="tel"?"tel":"text";input.dataset.type=item.type;input.setAttribute("aria-describedby",`help-${item.fieldId}`);const help=node("small","",`${item.dataClass} · ${item.exposure} response`);help.id=`help-${item.fieldId}`;field.append(caption,input,help);grid.append(field)}wrap.append(heading,grid);ui.sections.append(wrap)}
  renderPills(ui.documents,schema.documents.map(item=>`${label(item.title,lang)}${item.required?" *":""}`));renderPills(ui.actions,schema.actions.map(item=>label(item.title,lang)));ui.form.reset();ui.language.value=lang;ui.formStatus.textContent="";ui.title.focus()}
async function save(submit){if(!current)return;if(submit&&!document.querySelector("#declaration").checked){ui.formStatus.textContent="Confirm the declaration before submission.";return}const values={};for(const input of ui.form.querySelectorAll("[data-type]")){if(!input.value)continue;values[input.name]=input.dataset.type==="integer"?Number(input.value):input.value}const nonce=crypto.randomUUID();ui.formStatus.textContent=submit?"Submitting securely…":"Saving secure draft…";try{const response=await api(`/journey-workspaces/${channel}/drafts/${encodeURIComponent(current.journeyType)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draftId:`draft-${nonce}`,idempotencyKey:nonce,values,submit})});ui.formStatus.textContent=response.draft.status==="submitted"?"Application facts submitted with immutable schema lineage.":"Draft saved server-side. No values were retained by this browser.";ui.form.reset();activity(submit?"workspace_submitted":"workspace_draft_saved",current.journeyType)}catch(error){ui.formStatus.textContent=error.message}}
async function api(url,options={}){const response=await fetch(url,{...options,credentials:"same-origin",cache:"no-store",headers:{accept:"application/json",...(options.headers??{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message??`Request failed (${response.status}).`);return body}
function activity(activityType,journeyType){fetch("/activity/screen-events",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({screenId:"journey_workspace",activityType:activityType==="workspace_opened"?"screen_view":"action_intent",actionId:activityType,entityType:`product_journey_${journeyType}`})}).catch(()=>{})}
function networkState(){ui.offline.hidden=navigator.onLine;if(!navigator.onLine){ui.form.querySelectorAll("button").forEach(button=>button.disabled=true)}else ui.form.querySelectorAll("button").forEach(button=>button.disabled=false)}
function renderPills(target,items){target.replaceChildren();const list=node("div","pill-list");for(const item of items)list.append(node("span","pill",item));target.append(list)}
function state(message,error=false){ui.status.textContent=message;ui.status.classList.toggle("error",error)}function label(value,lang){return value?.[lang]??value?.en??""}function node(tag,className,text){const value=document.createElement(tag);if(className)value.className=className;if(text)value.textContent=text;return value}
