import { checkedValues, rupeesToPaise } from "/agent-studio/agent-studio-state.js";

const ui = Object.fromEntries(["home-link", "staff-link", "refresh", "status", "role-view", "template-gallery", "agent-form", "template-id", "contract-id", "model", "instructions", "action-scope", "simulate", "simulation-preview", "preview-content", "approval-content", "memory-store-id", "workflow-select", "commercial-form", "commercial-contract-id", "commercial-valid-until", "commercial-monthly-fee", "commercial-per-execution", "commercial-templates", "contract-actions", "budget-form", "budget-id", "budget-contract", "budget-paise", "budget-valid-until", "budget-actions", "budget-monitor", "installation-list", "approval-form", "approval-installation", "approval-role", "approval-ref", "activation-form", "activation-installation", "report-content", "workflow-form", "workflow-steps", "workflow-list", "add-step", "knowledge-form", "knowledge-list", "memory-form", "memory-list", "test-form", "test-installation", "test-list", "test-results", "version-form", "version-id", "version-installation", "version-test-run", "version-list", "release-readiness", "rollback-form", "rollback-id", "rollback-installation", "rollback-version", "rollback-reason", "rollback-list", "operations-queue", "compare-form", "compare-from", "compare-to", "comparison-result"].map((id) => [id.replaceAll("-", "_"), document.getElementById(id)]));
Object.assign(ui, Object.fromEntries(["provider-form", "provider-installation", "provider-list", "admission-list"].map((id) => [id.replaceAll("-", "_"), document.getElementById(id)])));
const tenantId = decodeURIComponent(location.pathname.match(/^\/t\/([^/]+)/)?.[1] ?? "");
const basePath = `/t/${encodeURIComponent(tenantId)}`;
let marketplace; let workspace; let registry; let selectedTemplate;
let selectedCategory = "all";
let workflowSteps = [{ type: "receive", label: "Receive the case" }, { type: "prepare", label: "Prepare the draft" }, { type: "human_review", label: "A staff member reviews it" }];
const studioViews = {
  create: { label: "Create", title: "Design an assistant for a banking journey", description: "Start from an approved pattern, set its boundaries and review what it may do.", anchors: ["agent-form", "simulation-preview", "approval-readiness", "workflow-form"] },
  knowledge: { label: "Knowledge & memory", title: "Control what assistants know and remember", description: "Register approved sources and privacy-controlled memory without mixing them with borrower records.", anchors: ["knowledge-form", "memory-form"] },
  "test-release": { label: "Test & release", title: "Prove the assistant is ready", description: "Rehearse normal and difficult cases, publish a tested version and safely return to an earlier one.", anchors: ["test-form", "version-form", "rollback-form"] },
  operations: { label: "Operations", title: "Run and improve your bank’s assistants", description: "See work needing attention, manage spending and compare existing assistants.", anchors: ["commercial-form", "operations-queue", "installation-list"] },
  governance: { label: "Governance", title: "Approve, activate and oversee", description: "Keep independent approvals, provider evidence and activity oversight together.", anchors: ["provider-form", "approval-form", "report-content"] }
};
let activeStudioView = normaliseStudioView(location.hash.slice(1));

ui.home_link.href = `${basePath}/`; ui.staff_link.href = `${basePath}/staff/`;
ui.refresh.addEventListener("click", load);
ui.template_gallery.addEventListener("click", (event) => { const button = event.target.closest("[data-template-id]"); if (button) selectTemplate(button.dataset.templateId); });
ui.simulate.addEventListener("click", preview);
ui.agent_form.addEventListener("submit", submitInstallation);
ui.commercial_form.addEventListener("submit", submitContract);
ui.budget_form.addEventListener("submit", submitBudget);
ui.budget_actions.addEventListener("click", approveBudget);
ui.contract_actions.addEventListener("click", commercialAction);
ui.approval_form.addEventListener("submit", submitApproval);
ui.activation_form.addEventListener("submit", submitActivation);
ui.installation_list.addEventListener("click", lifecycleAction);
ui.add_step.addEventListener("click", () => { if (workflowSteps.length < 12) { workflowSteps.push({ type: "check", label: "Check information" }); renderWorkflowCanvas(); } });
ui.workflow_steps.addEventListener("click", workflowStepAction);
ui.workflow_form.addEventListener("submit", submitWorkflow);
ui.knowledge_form.addEventListener("submit", submitKnowledgePack);
ui.knowledge_list.addEventListener("click", approveKnowledgePack);
ui.memory_form.addEventListener("submit", submitMemoryStore);
ui.memory_list.addEventListener("click", approveMemoryStore);
ui.test_form.addEventListener("submit", submitTestSuite);
ui.test_list.addEventListener("click", runTestSuite);
ui.version_form.addEventListener("submit", submitVersion);
ui.version_installation.addEventListener("change", renderReleaseReadiness);
ui.version_test_run.addEventListener("change", renderReleaseReadiness);
ui.rollback_form.addEventListener("submit", submitRollback);
ui.rollback_list.addEventListener("click", approveRollback);
ui.role_view.addEventListener("change", renderOperationsQueue);
ui.operations_queue.addEventListener("click", reviewProposal);
ui.provider_form.addEventListener("submit", submitProviderEvidence);
ui.provider_list.addEventListener("click", approveProviderEvidence);
ui.compare_form.addEventListener("submit", submitComparison);
document.querySelectorAll("[data-start-mode]").forEach((button) => button.addEventListener("click", () => startMode(button.dataset.startMode)));
document.getElementById("journey-filter").addEventListener("change", (event) => { selectedCategory = event.target.value; renderTemplates(); });
document.getElementById("workspace-nav").addEventListener("click", (event) => { const button = event.target.closest("[data-studio-view]"); if (button) setStudioView(button.dataset.studioView, true); });
document.getElementById("workspace-nav").addEventListener("keydown", navigateStudioViews);
window.addEventListener("hashchange", () => setStudioView(location.hash.slice(1), false));
configureStudioViews();
setStudioView(activeStudioView, false);
void load();

async function load() {
  setStatus("Loading governed Agent Studio…");
  try {
    [marketplace, workspace, registry] = await Promise.all([request("/ai/marketplace"), request("/ai/agents"), request("/ai/models")]);
    selectedTemplate ??= marketplace.templates[0];
    render(); setStatus("");
  } catch (error) { setStatus(error.message, true); }
}

function render() { renderTemplates(); renderJourneyEntitlements(); renderContracts(); renderModels(); renderCommercialTemplates(); renderCommercialActions(); renderBudgetActions(); renderActivationSelectors(); renderWorkflowCanvas(); renderStudioAssets(); renderOperationsQueue(); renderProviderEvidence(); selectTemplate(selectedTemplate.templateId, false); renderReadiness(); renderInstallations(); renderWorkspaceCount(); void renderReport(); }
function normaliseStudioView(value) { return Object.hasOwn(studioViews, value) ? value : "create"; }
function configureStudioViews() { for (const [view, definition] of Object.entries(studioViews)) for (const id of definition.anchors) document.getElementById(id)?.closest(".panel")?.setAttribute("data-workspace-section", view); }
function setStudioView(value, updateHash) { activeStudioView = normaliseStudioView(value); document.querySelectorAll("[data-workspace-section]").forEach((section) => { section.hidden = section.dataset.workspaceSection !== activeStudioView; }); const creating = activeStudioView === "create"; document.querySelector(".start-panel").hidden = !creating; document.querySelector(".stepper").hidden = !creating; document.querySelector(".catalogue-panel").hidden = !creating; document.querySelector(".layout").classList.toggle("workspace-wide", !creating); document.querySelectorAll("[data-studio-view]").forEach((button) => { if (button.dataset.studioView === activeStudioView) button.setAttribute("aria-current", "page"); else button.removeAttribute("aria-current"); }); const definition = studioViews[activeStudioView]; const intro = document.getElementById("workspace-intro"); intro.querySelector(".eyebrow").textContent = definition.label; intro.querySelector("h2").textContent = definition.title; intro.querySelector("p:last-child").textContent = definition.description; renderWorkspaceCount(); if (updateHash) history.replaceState(null, "", `#${activeStudioView}`); }
function navigateStudioViews(event) { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; const buttons = [...event.currentTarget.querySelectorAll("[data-studio-view]")]; const current = buttons.findIndex((button) => button.dataset.studioView === activeStudioView); const next = event.key === "Home" ? 0 : event.key === "End" ? buttons.length - 1 : (current + (event.key === "ArrowRight" ? 1 : -1) + buttons.length) % buttons.length; event.preventDefault(); buttons[next].focus(); buttons[next].click(); }
function renderWorkspaceCount() { const count = document.getElementById("workspace-count"); if (!workspace) { count.textContent = ""; return; } const totals = { create: marketplace?.templates?.length ?? 0, knowledge: (workspace.knowledgePacks?.length ?? 0) + (workspace.memoryStores?.length ?? 0), "test-release": (workspace.testSuites?.length ?? 0) + (workspace.agentVersions?.length ?? 0), operations: workspace.operationsQueue?.length ?? 0, governance: workspace.installations?.filter((item) => item.status === "pending_approval").length ?? 0 }; const nouns = { create: "available templates", knowledge: "governed resources", "test-release": "tests and versions", operations: "items needing attention", governance: "awaiting approval" }; count.textContent = `${totals[activeStudioView]} ${nouns[activeStudioView]}`; }
function renderJourneyEntitlements() { const products = workspace.enabledProductTypes ?? []; document.getElementById("enabled-products").replaceChildren(...products.map((item) => option(item, item.replaceAll("_", " ")))); document.getElementById("enabled-journeys").textContent = products.length ? `Enabled for your bank: ${products.map((item) => item.replaceAll("_", " ")).join(", ")}.` : "No active banking journey entitlement is available. Creation will be blocked."; }
function renderTemplates() { ui.template_gallery.replaceChildren(...marketplace.templates.map((template) => {
  const button = document.createElement("button"); button.type = "button"; button.className = "template-card"; button.dataset.templateId = template.templateId; button.setAttribute("aria-current", String(template.templateId === selectedTemplate?.templateId));
  button.innerHTML = `<strong>${escapeHtml(template.name)}</strong><small>${escapeHtml(template.category)} · autonomy ${escapeHtml(template.maximumAutonomy)}</small><span class="status-tag pending">Proposal only</span>`; return button;
}).filter((button) => selectedCategory === "all" || marketplace.templates.find((template) => template.templateId === button.dataset.templateId)?.category === selectedCategory)); }
function renderContracts() { const active = workspace.pricingContracts.filter((item) => item.status === "active"); ui.contract_id.replaceChildren(option("", "Select an active contract"), ...active.map((item) => option(item.contractId, item.contractId))); ui.budget_contract.replaceChildren(option("", "Select an active contract"), ...active.map((item) => option(item.contractId, item.contractId))); }
function renderModels() { const models = Object.values(registry.models ?? {}).filter((model) => model.status === "active"); ui.model.replaceChildren(option("", models.length ? "Select an active model" : "No active model is available"), ...models.map((model) => option(`${model.modelId}|${model.version}`, `${model.modelId} · ${model.version}`))); }
function renderCommercialTemplates() { ui.commercial_templates.replaceChildren(...marketplace.templates.map((template) => { const label = document.createElement("label"); label.className = "action-option"; const input = document.createElement("input"); input.type = "checkbox"; input.name = "commercialTemplates"; input.value = template.templateId; label.append(input, document.createTextNode(template.name)); return label; })); }
function selectTemplate(templateId, announce = true) { selectedTemplate = marketplace.templates.find((item) => item.templateId === templateId); ui.template_id.value = selectedTemplate.templateId; renderTemplates(); ui.action_scope.replaceChildren(...selectedTemplate.allowedActions.map((action) => actionCheckbox(action))); if (announce) { preview(); renderReadiness(); } }
function actionCheckbox(action) { const label = document.createElement("label"); label.className = "action-option"; const input = document.createElement("input"); input.type = "checkbox"; input.name = "allowedActions"; input.value = action; input.checked = true; label.append(input, document.createTextNode(action)); return label; }
function preview() { const actions = values("allowedActions"); const content = document.createElement("div"); content.className = "preview-grid"; content.append(previewItem("Authority", "Proposal only — no credit decision, pricing, fund movement or policy change."), previewItem("Selected actions", actions.length ? actions.join(", ") : "No action selected; installation cannot be submitted."), previewItem("Bounded scope", "A tenant can narrow approved actions but cannot expand the marketplace template's authority."), previewItem("Human handoff", selectedTemplate.customerFacing ? "Customer-facing work must carry disclosure and a human handoff path." : "A human reviews every material proposal before any downstream action."), previewItem("Synthetic runtime", "Preview is configuration-only. It does not call a model or process borrower data.")); ui.preview_content.replaceChildren(content); renderReadiness(); }
function renderReadiness() { const fields = new FormData(ui.agent_form); const ready = [fields.get("contractId"), fields.get("model"), fields.get("installationId"), fields.get("workloadPrincipalId"), fields.get("humanSponsorPrincipalId"), fields.get("configurationRef"), fields.get("instructions")].every(Boolean) && values("allowedActions").length > 0; const grid = document.createElement("div"); grid.className = "readiness-grid"; grid.append(readinessItem(ready, ready ? "Configuration can be submitted" : "Configuration is incomplete", ready ? "Submission creates a pending installation; it cannot activate the worker." : "Complete the required scope, model, contract and accountability fields."), readinessItem(false, "Four distinct human approvals", "Model owner, validator, human reviewer and model-risk manager must approve independently."), readinessItem(false, "Activation is fail-closed", "Activation also requires current FST-034 staffing and an isolated control-engine decision.")); ui.approval_content.replaceChildren(grid); }
async function submitInstallation(event) { event.preventDefault(); const form = new FormData(ui.agent_form); const [modelId, modelVersion] = String(form.get("model")).split("|"); if (!modelId || !values("allowedActions").length) return setStatus("Select an active model and at least one template action.", true);
  try { const instructions = String(form.get("instructions")); const payload = { installationId: form.get("installationId"), templateId: selectedTemplate.templateId, contractId: form.get("contractId"), modelId, modelVersion, workloadPrincipalId: form.get("workloadPrincipalId"), humanSponsorPrincipalId: form.get("humanSponsorPrincipalId"), promptRef: `agent-studio/prompt/${form.get("installationId")}`, promptHash: await sha256(instructions), configurationRef: form.get("configurationRef"), allowedActions: values("allowedActions"), languages: split(form.get("languages")), productTypes: split(form.get("products")), dataScopes: split(form.get("dataScopes")), memoryMode: form.get("memoryMode"), memoryStoreId: form.get("memoryStoreId") || undefined, workflowId: form.get("workflowId") || undefined, knowledgeSources: parseKnowledge(form.get("knowledgeSources")) };
    await request("/ai/agents/installations", { method: "POST", body: JSON.stringify(payload) }); setStatus("Installation submitted. It remains proposal-only until four independent human approvals and activation checks pass."); await load(); } catch (error) { setStatus(error.message, true); }
}
async function submitContract(event) { event.preventDefault(); const templateIds = values("commercialTemplates"); if (!templateIds.length) return setStatus("Select at least one entitled worker template.", true); const validUntil = new Date(ui.commercial_valid_until.value); if (Number.isNaN(validUntil.getTime())) return setStatus("Provide a contract end date.", true);
  try { const pricing = { monthly_platform_fee_paise: rupeesToPaise(ui.commercial_monthly_fee.value), included_executions: "0", included_input_tokens: "0", included_output_tokens: "0", per_execution_paise: rupeesToPaise(ui.commercial_per_execution.value), per_1k_input_tokens_paise: "0", per_1k_output_tokens_paise: "0" }; await request("/ai/pricing-contracts", { method: "POST", body: JSON.stringify({ contractId: ui.commercial_contract_id.value, templateIds, pricing, effectiveFrom: new Date().toISOString(), validUntil: validUntil.toISOString() }) }); setStatus("Pricing contract proposed. An independent commercial checker must approve it before installation."); ui.commercial_form.reset(); await load(); } catch (error) { setStatus(error.message, true); }
}
function renderCommercialActions() { const pending = workspace.pricingContracts.filter((item) => item.status === "pending_approval"); ui.contract_actions.replaceChildren(...pending.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; const button = document.createElement("button"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approveContract = item.contractId; button.textContent = "Approve contract"; row.append(text("strong", item.contractId), text("small", "Independent commercial approval required."), button); return row; })); }
function renderBudgetActions() { const budgets = workspace.usageBudgets ?? []; const pending = budgets.filter((item) => item.status === "pending_approval"); ui.budget_actions.replaceChildren(...pending.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; const button = text("button", "Approve spending limit"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approveBudget = item.budgetId; row.append(text("strong", item.budgetId), text("small", `Maximum ₹${paiseToRupees(item.limits.maxChargePaise)} · independent finance approval required`), button); return row; })); const active = budgets.filter((item) => item.status === "active"); ui.budget_monitor.className = active.length ? "preview-grid" : "preview-grid empty"; ui.budget_monitor.replaceChildren(...(active.length ? active.map((item) => previewItem(item.budgetId, `Approved ceiling ₹${paiseToRupees(item.limits.maxChargePaise)} · valid until ${new Date(item.validUntil).toLocaleDateString("en-IN")}`)) : [text("span", "No approved spending limits.")])); }
function renderActivationSelectors() { const pending = workspace.installations.filter((item) => item.status === "pending_approval"); const options = [option("", pending.length ? "Select a pending installation" : "No pending installation") , ...pending.map((item) => option(item.installationId, `${item.installationId} · ${Object.keys(item.approvedByRole ?? {}).length}/4 approvals`))]; ui.approval_installation.replaceChildren(...options); ui.activation_installation.replaceChildren(...options.map((item) => item.cloneNode(true))); const all = [option("", "Select an assistant"), ...workspace.installations.map((item) => option(item.installationId, item.installationId))]; ui.test_installation.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.compare_from.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.compare_to.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.version_installation.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.rollback_installation.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.provider_installation.replaceChildren(...all.map((item) => item.cloneNode(true))); ui.version_test_run.replaceChildren(option("", "Select a passing rehearsal"), ...(workspace.testRuns ?? []).filter((item) => item.status === "passed").map((item) => option(item.runId, `${item.runId} · ${item.scorePercent}%`))); ui.rollback_version.replaceChildren(option("", "Select a published version"), ...(workspace.agentVersions ?? []).map((item) => option(item.versionId, `${item.versionId} · version ${item.versionNumber}`))); ui.memory_store_id.replaceChildren(option("", "Not required"), ...(workspace.memoryStores ?? []).filter((item) => item.status === "active").map((item) => option(item.memoryStoreId, item.name))); if (ui.workflow_select) ui.workflow_select.replaceChildren(option("", "Not required"), ...(workspace.workflowDrafts ?? []).map((item) => option(item.workflowId, `${item.name} (${item.steps.length} steps)`))); }

function renderWorkflowCanvas() { ui.workflow_steps.replaceChildren(...workflowSteps.map((step, index) => { const card = document.createElement("article"); card.className = "workflow-step"; const number = text("span", String(index + 1)); number.className = "step-number"; const select = document.createElement("select"); select.dataset.stepType = index; for (const [value, label] of [["receive", "Receive a case"], ["check", "Check information"], ["prepare", "Prepare a draft"], ["request_information", "Request information"], ["route", "Route to a team"], ["human_review", "Human review"], ["notify", "Prepare a notification"], ["close", "Close the task"]]) select.append(option(value, label)); select.value = step.type; const input = document.createElement("input"); input.value = step.label; input.dataset.stepLabel = index; input.setAttribute("aria-label", `Step ${index + 1} description`); const remove = document.createElement("button"); remove.type = "button"; remove.className = "btn btn-secondary btn-sm"; remove.dataset.removeStep = index; remove.textContent = "Remove"; card.append(number, select, input, remove); return card; })); ui.workflow_steps.querySelectorAll("select,input").forEach((field) => field.addEventListener("change", updateWorkflowStep)); }
function updateWorkflowStep(event) { const index = Number(event.target.dataset.stepType ?? event.target.dataset.stepLabel); if (event.target.dataset.stepType !== undefined) workflowSteps[index].type = event.target.value; else workflowSteps[index].label = event.target.value; }
function workflowStepAction(event) { const button = event.target.closest("[data-remove-step]"); if (!button || workflowSteps.length <= 2) return; workflowSteps.splice(Number(button.dataset.removeStep), 1); renderWorkflowCanvas(); }
async function submitWorkflow(event) { event.preventDefault(); const form = new FormData(ui.workflow_form); try { await request("/ai/agents/workflows", { method: "POST", body: JSON.stringify({ workflowId: form.get("workflow-id") ?? document.getElementById("workflow-id").value, name: document.getElementById("workflow-id").value, templateId: selectedTemplate.templateId, productTypes: split(document.getElementById("workflow-products").value), steps: workflowSteps }) }); setStatus("Work plan saved as a governed draft."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitKnowledgePack(event) { event.preventDefault(); try { const content = document.getElementById("knowledge-content").value; await request("/ai/agents/knowledge-packs", { method: "POST", body: JSON.stringify({ packId: slug(document.getElementById("knowledge-pack-id").value), name: document.getElementById("knowledge-pack-id").value, version: document.getElementById("knowledge-version").value, sourceRef: document.getElementById("knowledge-source-ref").value, validUntil: document.getElementById("knowledge-valid-until").value, contentHash: await sha256(content), memoryMode: "none" }) }); setStatus("Knowledge pack registered with checksum and review date. Raw policy text was not sent."); ui.knowledge_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function approveKnowledgePack(event) { const button = event.target.closest("[data-approve-pack]"); if (!button) return; const approvalRef = window.prompt("Independent knowledge approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/agents/knowledge-packs/${encodeURIComponent(button.dataset.approvePack)}/approve`, { method: "POST", body: JSON.stringify({ approvalRef: approvalRef.trim() }) }); setStatus("Knowledge pack approved by an independent checker."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitMemoryStore(event) { event.preventDefault(); const get = (id) => document.getElementById(id).value; try { const name = get("memory-store-name"); await request("/ai/agents/memory-stores", { method: "POST", body: JSON.stringify({ memoryStoreId: slug(name), name, purpose: get("memory-purpose"), allowedFields: split(get("memory-fields")), region: "ap-south-1", retentionDays: Number(get("memory-retention")), consentRef: get("memory-consent-ref"), accessPolicyRef: get("memory-access-ref"), correctionProcessRef: get("memory-correction-ref"), deletionProcessRef: get("memory-deletion-ref"), legalHoldPolicyRef: get("memory-hold-ref"), encryptionRef: get("memory-encryption-ref") }) }); setStatus("Memory store proposed. Persistent memory remains unavailable until privacy approval."); ui.memory_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function approveMemoryStore(event) { const button = event.target.closest("[data-approve-memory]"); if (!button) return; const approvalRef = window.prompt("Independent privacy approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/agents/memory-stores/${encodeURIComponent(button.dataset.approveMemory)}/approve`, { method: "POST", body: JSON.stringify({ approvalRef: approvalRef.trim() }) }); setStatus("Governed memory store approved for its declared purpose and fields."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitTestSuite(event) { event.preventDefault(); try { await request("/ai/agents/test-suites", { method: "POST", body: JSON.stringify({ suiteId: slug(document.getElementById("test-suite-id").value), name: document.getElementById("test-suite-id").value, installationId: ui.test_installation.value, cases: [{ caseId: "expected", kind: "expected", scenario: document.getElementById("expected-scenario").value, expectedOutcome: "proposal" }, { caseId: "adverse", kind: "adverse", scenario: document.getElementById("adverse-scenario").value, expectedOutcome: "human_review" }] }) }); setStatus("Test set saved with normal and adverse cases."); ui.test_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function runTestSuite(event) { const button = event.target.closest("[data-run-suite]"); if (!button) return; try { await request(`/ai/agents/test-suites/${encodeURIComponent(button.dataset.runSuite)}/runs`, { method: "POST", body: JSON.stringify({ runId: `${button.dataset.runSuite}-${Date.now()}` }) }); setStatus("Rehearsal completed by the governed server harness. It verifies control wiring, not live-model quality."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitVersion(event) { event.preventDefault(); try { await request("/ai/agents/versions", { method: "POST", body: JSON.stringify({ versionId: slug(ui.version_id.value), installationId: ui.version_installation.value, testRunId: ui.version_test_run.value }) }); setStatus("Immutable tested configuration version published. Live-provider admission remains separate."); ui.version_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitRollback(event) { event.preventDefault(); try { await request("/ai/agents/rollbacks", { method: "POST", body: JSON.stringify({ rollbackId: slug(ui.rollback_id.value), installationId: ui.rollback_installation.value, targetVersionId: ui.rollback_version.value, reason: ui.rollback_reason.value }) }); setStatus("Rollback requested. A different authenticated checker must approve it."); ui.rollback_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function approveRollback(event) { const button = event.target.closest("[data-approve-rollback]"); if (!button) return; const approvalRef = window.prompt("Independent change or incident approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/agents/rollbacks/${encodeURIComponent(button.dataset.approveRollback)}/approve`, { method: "POST", body: JSON.stringify({ approvalRef: approvalRef.trim() }) }); setStatus("Rollback completed with independent approval and retained evidence."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitComparison(event) { event.preventDefault(); try { const comparison = await request("/ai/agents/compare", { method: "POST", body: JSON.stringify({ fromInstallationId: ui.compare_from.value, toInstallationId: ui.compare_to.value }) }); const cards = Object.entries(comparison.changes).filter(([, change]) => change.changed || change.added?.length || change.removed?.length).map(([key, change]) => previewItem(key.replaceAll(/([A-Z])/g, " $1"), change.changed ? `${change.from || "none"} → ${change.to || "none"}` : `Added: ${change.added.join(", ") || "none"}; removed: ${change.removed.join(", ") || "none"}`)); ui.comparison_result.className = "preview-grid"; ui.comparison_result.replaceChildren(...(cards.length ? cards : [previewItem("No material change", "The governed fields match.")])); } catch (error) { setStatus(error.message, true); } }
function renderStudioAssets() { renderRecords(ui.workflow_list, workspace.workflowDrafts, (item) => `${item.steps.length} steps · ${item.productTypes.join(", ")}`); renderKnowledgePacks(); renderMemoryStores(); renderTestSuites(); renderTestResults(); renderRecords(ui.version_list, workspace.agentVersions, (item) => `Version ${item.versionNumber} · passed rehearsal ${item.testRunId}`); renderRollbacks(); renderReleaseReadiness(); }
function renderKnowledgePacks() { const records = workspace.knowledgePacks ?? []; if (!records.length) return renderRecords(ui.knowledge_list, [], () => ""); ui.knowledge_list.className = "lifecycle-list"; ui.knowledge_list.replaceChildren(...records.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; row.append(text("strong", item.name), text("small", `Version ${item.version} · ${item.status} · review by ${new Date(item.validUntil).toLocaleDateString("en-IN")}`)); if (item.status === "draft") { const button = text("button", "Approve as checker"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approvePack = item.packId; row.append(button); } return row; })); }
function renderMemoryStores() { const records = workspace.memoryStores ?? []; if (!records.length) return renderRecords(ui.memory_list, [], () => ""); ui.memory_list.className = "lifecycle-list"; ui.memory_list.replaceChildren(...records.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; row.append(text("strong", item.name), text("small", `${item.status} · ${item.retentionDays} days · ${item.allowedFields.join(", ")} · India region`)); if (item.status === "pending_approval") { const button = text("button", "Approve as privacy checker"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approveMemory = item.memoryStoreId; row.append(button); } return row; })); }
function renderTestSuites() { const suites = workspace.testSuites ?? []; if (!suites.length) { ui.test_list.className = "lifecycle-list empty"; ui.test_list.textContent = "No test sets yet."; return; } ui.test_list.className = "lifecycle-list"; ui.test_list.replaceChildren(...suites.map((suite) => { const row = document.createElement("article"); row.className = "lifecycle-item"; const button = text("button", "Rehearse controls"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.runSuite = suite.suiteId; row.append(text("strong", suite.name), text("small", `${suite.caseCount} cases · includes adverse testing`), button); return row; })); }
function renderTestResults() { const runs = workspace.testRuns ?? []; if (!runs.length) { ui.test_results.className = "preview-grid empty"; ui.test_results.textContent = "No rehearsal results yet."; return; } ui.test_results.className = "preview-grid"; ui.test_results.replaceChildren(...runs.slice(-4).map((run) => previewItem(`${run.status === "passed" ? "Passed" : "Needs attention"} · ${run.scorePercent}%`, `${run.passedCount}/${run.caseCount} cases · adverse ${run.adversePassed ? "passed" : "failed"} · synthetic rehearsal`))); }
function renderRollbacks() { const records = workspace.rollbackRequests ?? []; if (!records.length) { ui.rollback_list.className = "lifecycle-list empty"; ui.rollback_list.textContent = "No rollback requests."; return; } ui.rollback_list.className = "lifecycle-list"; ui.rollback_list.replaceChildren(...records.map((record) => { const row = document.createElement("article"); row.className = "lifecycle-item"; row.append(text("strong", record.rollbackId), text("small", `${record.targetVersionId} · ${record.status} · ${record.reason}`)); if (record.status === "pending_approval") { const button = text("button", "Approve as independent checker"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approveRollback = record.rollbackId; row.append(button); } return row; })); }
function renderReleaseReadiness() { const installation = workspace.installations.find((item) => item.installationId === ui.version_installation.value); const run = (workspace.testRuns ?? []).find((item) => item.runId === ui.version_test_run.value); const cards = [readinessItem(Boolean(run?.status === "passed"), run?.status === "passed" ? "All rehearsal cases passed" : "Passing rehearsal needed", run ? `${run.scorePercent}% · adverse ${run.adversePassed ? "passed" : "failed"}` : "Run the normal and difficult cases."), readinessItem(Object.keys(installation?.approvedByRole ?? {}).length === 4, `${Object.keys(installation?.approvedByRole ?? {}).length}/4 human approvals`, "Owner, validator, reviewer and model-risk manager must be independent."), readinessItem(false, "Live-provider certification separate", "Publishing here versions configuration; it does not admit a live model provider." )]; ui.release_readiness.className = "readiness-grid"; ui.release_readiness.replaceChildren(...cards); }
function renderRecords(container, records = [], detail) { if (!records.length) { container.className = "lifecycle-list empty"; return; } container.className = "lifecycle-list"; container.replaceChildren(...records.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; row.append(text("strong", item.name), text("small", detail(item))); return row; })); }
async function commercialAction(event) { const button = event.target.closest("[data-approve-contract]"); if (!button) return; const approvalRef = window.prompt("Commercial approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/pricing-contracts/${encodeURIComponent(button.dataset.approveContract)}/approve`, { method: "POST", body: JSON.stringify({ commercialApprovalRef: approvalRef.trim() }) }); setStatus("Contract approved for entitled installations."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitBudget(event) { event.preventDefault(); const until = new Date(ui.budget_valid_until.value); if (!ui.budget_contract.value || Number.isNaN(until.getTime())) return setStatus("Budget requires an active contract and end date.", true); try { const limits = { maxExecutions: "999999", maxInputTokens: "999999999", maxOutputTokens: "999999999", maxChargePaise: rupeesToPaise(ui.budget_paise.value) }; await request("/ai/usage-budgets", { method: "POST", body: JSON.stringify({ budgetId: ui.budget_id.value, contractId: ui.budget_contract.value, limits, effectiveFrom: new Date().toISOString(), validUntil: until.toISOString() }) }); setStatus("Hard usage budget proposed for independent approval."); ui.budget_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function approveBudget(event) { const button = event.target.closest("[data-approve-budget]"); if (!button) return; const approvalRef = window.prompt("Independent finance approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/usage-budgets/${encodeURIComponent(button.dataset.approveBudget)}/approve`, { method: "POST", body: JSON.stringify({ commercialApprovalRef: approvalRef.trim() }) }); setStatus("Spending limit approved with an exact hard ceiling."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitApproval(event) { event.preventDefault(); if (!ui.approval_installation.value || !ui.approval_ref.value.trim()) return setStatus("Select the installation and enter an independent approval reference.", true); try { await request(`/ai/agents/installations/${encodeURIComponent(ui.approval_installation.value)}/approvals/${encodeURIComponent(ui.approval_role.value)}`, { method: "POST", body: JSON.stringify({ approvalRef: ui.approval_ref.value.trim() }) }); setStatus("Approval recorded if your authenticated role and independence requirements are satisfied."); ui.approval_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitActivation(event) { event.preventDefault(); const form = new FormData(ui.activation_form); const governanceEvidence = Object.fromEntries([...form.entries()].filter(([key]) => key !== "installationId")); if (!ui.activation_installation.value) return setStatus("Select a pending installation for activation.", true); try { await request(`/ai/agents/installations/${encodeURIComponent(ui.activation_installation.value)}/activate`, { method: "POST", body: JSON.stringify({ governanceEvidence }) }); setStatus("Activation completed only after the isolated control engine allowed the current evidence and staffing state."); ui.activation_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
function renderInstallations() { const installations = [...workspace.installations].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); if (!installations.length) { ui.installation_list.className = "lifecycle-list empty"; ui.installation_list.textContent = "No tenant installations yet."; return; } ui.installation_list.className = "lifecycle-list"; ui.installation_list.replaceChildren(...installations.map((installation) => { const item = document.createElement("article"); item.className = "lifecycle-item"; const approvals = Object.keys(installation.approvedByRole ?? {}).length; item.append(text("strong", installation.installationId), text("span", `${installation.templateId} · ${installation.status} · ${approvals}/4 approvals`), text("small", `Model ${installation.modelId} ${installation.modelVersion} · ${installation.allowedActions.join(", ")}`)); const actions = document.createElement("div"); actions.className = "inline-actions"; const exportButton = text("button", "Export setup"); exportButton.type = "button"; exportButton.className = "btn btn-secondary btn-sm"; exportButton.dataset.exportId = installation.installationId; actions.append(exportButton); if (installation.status === "active") { const button = text("button", "Suspend"); button.type = "button"; button.className = "btn btn-danger btn-sm"; button.dataset.suspendId = installation.installationId; actions.append(button); } if (installation.status !== "retired") { const retire = text("button", "Retire"); retire.type = "button"; retire.className = "btn btn-secondary btn-sm"; retire.dataset.retireId = installation.installationId; actions.append(retire); } item.append(actions); return item; })); }
async function lifecycleAction(event) { const exportButton = event.target.closest("[data-export-id]"); if (exportButton) { try { const record = await request(`/ai/agents/installations/${encodeURIComponent(exportButton.dataset.exportId)}/export`); downloadJson(`${exportButton.dataset.exportId}.json`, record); setStatus("Configuration exported without approvals or borrower data."); } catch (error) { setStatus(error.message, true); } return; } const retireButton = event.target.closest("[data-retire-id]"); if (retireButton) { const reason = window.prompt("Why is this assistant being retired?"); if (!reason?.trim()) return; try { await request(`/ai/agents/installations/${encodeURIComponent(retireButton.dataset.retireId)}/retire`, { method: "POST", body: JSON.stringify({ reason: reason.trim(), exportRef: `agent-studio/export/${retireButton.dataset.retireId}` }) }); setStatus("Assistant retired. Its evidence and history remain available."); await load(); } catch (error) { setStatus(error.message, true); } return; } const button = event.target.closest("[data-suspend-id]"); if (!button) return; const reason = window.prompt("Reason for immediate suspension (required):"); if (!reason?.trim()) return; const incidentRef = window.prompt("Incident reference (required):"); if (!incidentRef?.trim()) return; try { await request(`/ai/agents/installations/${encodeURIComponent(button.dataset.suspendId)}/suspend`, { method: "POST", body: JSON.stringify({ reason: reason.trim(), incidentRef: incidentRef.trim() }) }); setStatus("Installation suspended. New execution authorization is blocked."); await load(); } catch (error) { setStatus(error.message, true); } }
async function renderReport() { try { const report = await request("/ai/agents/governance-report"); const metrics = report.summary ?? report; const entries = Object.entries(metrics).filter(([, value]) => typeof value === "number" || typeof value === "string").slice(0, 8); if (!entries.length) { ui.report_content.className = "preview-grid empty"; ui.report_content.textContent = "No governed activity yet."; return; } ui.report_content.className = "preview-grid"; ui.report_content.replaceChildren(...entries.map(([key, value]) => previewItem(key.replaceAll(/([A-Z])/g, " $1"), String(value)))); } catch (error) { ui.report_content.className = "preview-grid empty"; ui.report_content.textContent = `Report unavailable: ${error.message}`; } }
function renderOperationsQueue() { const role = ui.role_view.value; const records = (workspace.operationsQueue ?? []).filter((item) => role === "all" || role === "business" || item.ownerRole === role); if (!records.length) { ui.operations_queue.className = "lifecycle-list empty"; ui.operations_queue.textContent = "Nothing needs attention for this view."; return; } ui.operations_queue.className = "lifecycle-list"; ui.operations_queue.replaceChildren(...records.map((item) => { const row = document.createElement("article"); row.className = `lifecycle-item queue-${item.severity}`; row.append(text("strong", item.title), text("small", `Owner: ${item.ownerRole.replaceAll("_", " ")} · due ${new Date(item.dueAt).toLocaleDateString("en-IN")}`)); if (item.type === "proposal_review") { const actions = document.createElement("div"); actions.className = "inline-actions"; const accept = text("button", "Confirm proposal"); accept.type = "button"; accept.className = "btn btn-primary btn-sm"; accept.dataset.reviewExecution = item.resourceId; accept.dataset.reviewDisposition = "accepted"; const send = text("button", "Return to team"); send.type = "button"; send.className = "btn btn-secondary btn-sm"; send.dataset.reviewExecution = item.resourceId; send.dataset.reviewDisposition = "returned_for_changes"; actions.append(accept, send); row.append(actions); } return row; })); }
async function reviewProposal(event) { const button = event.target.closest("[data-review-execution]"); if (!button) return; const reviewRef = window.prompt("Your review record reference (required):"); if (!reviewRef?.trim()) return; try { await request(`/ai/agents/executions/${encodeURIComponent(button.dataset.reviewExecution)}/human-review`, { method: "POST", body: JSON.stringify({ disposition: button.dataset.reviewDisposition, reviewRef: reviewRef.trim() }) }); setStatus("Your review is recorded against the proposal's audit trail. The assistant cannot act on it without you."); await load(); } catch (error) { setStatus(error.message, true); } }
async function submitProviderEvidence(event) { event.preventDefault(); const get = (id) => document.getElementById(id).value; try { await request("/ai/agents/provider-evidence", { method: "POST", body: JSON.stringify({ evidenceId: get("provider-evidence-id"), installationId: ui.provider_installation.value, providerId: get("provider-id"), region: "ap-south-1", contractRef: get("provider-contract-ref"), securityRef: get("provider-security-ref"), residencyRef: get("provider-residency-ref"), monitoringRef: get("provider-monitoring-ref"), incidentExerciseRef: get("provider-incident-ref"), institutionUatRef: get("provider-uat-ref"), validUntil: get("provider-valid-until") }) }); setStatus("Provider evidence submitted. Production remains denied until independent approval and every admission gate passes."); ui.provider_form.reset(); await load(); } catch (error) { setStatus(error.message, true); } }
async function approveProviderEvidence(event) { const button = event.target.closest("[data-approve-provider]"); if (!button) return; const approvalRef = window.prompt("Independent provider-evidence approval reference:"); if (!approvalRef?.trim()) return; try { await request(`/ai/agents/provider-evidence/${encodeURIComponent(button.dataset.approveProvider)}/approve`, { method: "POST", body: JSON.stringify({ approvalRef: approvalRef.trim() }) }); setStatus("Provider evidence approved. LoanOS has reassessed production admission."); await load(); } catch (error) { setStatus(error.message, true); } }
function renderProviderEvidence() { const records = workspace.providerEvidence ?? []; if (!records.length) { ui.provider_list.className = "lifecycle-list empty"; ui.provider_list.textContent = "No provider evidence."; } else { ui.provider_list.className = "lifecycle-list"; ui.provider_list.replaceChildren(...records.map((item) => { const row = document.createElement("article"); row.className = "lifecycle-item"; row.append(text("strong", `${item.providerId} · ${item.status}`), text("small", `India region · valid until ${new Date(item.validUntil).toLocaleDateString("en-IN")}`)); if (item.status === "pending_approval") { const button = text("button", "Approve as independent checker"); button.type = "button"; button.className = "btn btn-secondary btn-sm"; button.dataset.approveProvider = item.evidenceId; row.append(button); } return row; })); } const admissions = workspace.productionAdmission ?? []; ui.admission_list.className = admissions.length ? "readiness-grid" : "readiness-grid empty"; ui.admission_list.replaceChildren(...(admissions.length ? admissions.map((item) => readinessItem(item.ready, `${item.installationId} · ${item.ready ? "admission controls pass" : "production denied"}`, item.ready ? "Repository evidence gates pass; institution authorization is still required." : item.reasons.join(", ").replaceAll("_", " "))) : [text("span", "Production admission remains denied.")])); }
function parseKnowledge(value) { return String(value || "").split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [ref, version, contentHash] = line.split("|").map((part) => part.trim()); if (!ref || !version || !/^[a-f0-9]{64}$/i.test(contentHash ?? "")) throw new Error("Each knowledge source must be reference | version | 64-character SHA-256."); return { ref, version, contentHash }; }); }
function values(name) { return checkedValues(name === "commercialTemplates" ? ui.commercial_form : ui.agent_form, name); }
function split(value) { return String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean); }
function slug(value) { return String(value).trim().toLowerCase().replaceAll(/[^a-z0-9]+/g, "-").replaceAll(/^-|-$/g, ""); }
function paiseToRupees(value) { return (BigInt(value ?? "0") / 100n).toLocaleString("en-IN") + (BigInt(value ?? "0") % 100n ? `.${(BigInt(value) % 100n).toString().padStart(2, "0")}` : ""); }
function downloadJson(name, value) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
function previewItem(title, detail) { const item = document.createElement("article"); item.className = "preview-item"; item.append(text("strong", title), text("span", detail)); return item; }
function readinessItem(good, title, detail) { const item = document.createElement("article"); item.className = `readiness-item ${good ? "good" : "warn"}`; item.append(text("strong", title), text("span", detail)); return item; }
function option(value, label) { const node = document.createElement("option"); node.value = value; node.textContent = label; return node; }
function text(tag, value) { const node = document.createElement(tag); node.textContent = value; return node; }
function escapeHtml(value) { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
async function sha256(value) { const bytes = new TextEncoder().encode(value); const hash = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function request(path, init = {}) { const response = await fetch(path, { headers: { "content-type": "application/json", ...(init.headers ?? {}) }, ...init }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message ?? "The requested agent operation was blocked."); return body; }
function setStatus(message, error = false) { ui.status.textContent = message; ui.status.classList.toggle("error", error); }
function startMode(mode) {
  document.querySelectorAll("[data-start-mode]").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.startMode === mode)));
  if (mode === "copy") {
    const source = workspace.installations.at(-1);
    if (!source) return setStatus("There is no existing assistant to copy yet. Start with a banking template instead.", true);
    selectTemplate(source.templateId);
    ui.agent_form.elements.installationId.value = `${source.installationId}-copy`;
    ui.agent_form.elements.humanSponsorPrincipalId.value = source.humanSponsorPrincipalId;
    ui.agent_form.elements.products.value = (source.productTypes ?? []).join(", ");
    ui.agent_form.elements.languages.value = (source.languages ?? []).join(", ");
    ui.agent_form.elements.dataScopes.value = (source.dataScopes ?? []).join(", ");
    ui.agent_form.elements.instructions.value = `Adapt the approved instructions from ${source.promptRef}. Describe the new assistant's job here.`;
    ui.contract_id.value = source.contractId;
    ui.model.value = `${source.modelId}|${source.modelVersion}`;
    ui.agent_form.elements.workloadPrincipalId.value = `${source.workloadPrincipalId}-copy`;
    ui.agent_form.elements.configurationRef.value = `${source.configurationRef}-copy`;
    ui.action_scope.querySelectorAll("input").forEach((input) => { input.checked = source.allowedActions.includes(input.value); });
    setStatus("Existing assistant copied as a new draft. Review every field before sending it for approval.");
  } else if (mode === "guided") {
    const template = selectedTemplate ?? marketplace.templates[0];
    ui.agent_form.reset(); selectTemplate(template.templateId);
    ui.agent_form.elements.languages.value = "en-IN";
    setStatus("Guided setup started. Describe the job in everyday language; advanced controls inherit from the selected safe template.");
  } else {
    document.querySelector(".catalogue-panel")?.scrollIntoView({ behavior: "smooth", block: "start" });
    setStatus("Choose the banking pattern closest to the work your team performs.");
  }
}
