const roles=[
  {id:"owner",icon:"TO",name:"Tenant owner",track:"Go-live & accountability",desc:"Lead safe tenant activation and keep organisational readiness current.",outcomes:["Readiness and staffing","Provider and control assurance","Evidence-led go-live"]},
  {id:"product",icon:"PA",name:"Product administrator",track:"Products & configuration",desc:"Turn approved product intent into governed, effective-dated configuration.",outcomes:["Product policy versions","Journey configuration","Maker-checker release"]},
  {id:"loan",icon:"LO",name:"Loan officer",track:"Origination & borrower journey",desc:"Move an application from consent to sanction without losing control evidence.",outcomes:["Consent and KYC","Decision referrals","KFS and sanction"]},
  {id:"operations",icon:"OS",name:"Operations & servicing",track:"Money movement & lifecycle",desc:"Operate disbursement, repayment, servicing and exceptions with exact lineage.",outcomes:["Disbursement readiness","Servicing controls","Exception resolution"]},
  {id:"compliance",icon:"CO",name:"Compliance officer",track:"Controls & assurance",desc:"Test obligations, investigate gaps and produce scoped, review-ready evidence.",outcomes:["Control traceability","KFS assurance","Integrity evidence packs"]},
  {id:"risk",icon:"RC",name:"Risk & credit manager",track:"Decision governance",desc:"Govern policy outcomes, referrals and overrides across the credit lifecycle.",outcomes:["Policy governance","Restrictive outcomes","Independent approval"]},
  {id:"integration",icon:"IA",name:"Integration administrator",track:"Providers & interfaces",desc:"Certify provider behaviour and keep credentials, callbacks and failure paths safe.",outcomes:["Provider certification","Timeout and replay safety","Live-use evidence"]},
  {id:"support",icon:"SP",name:"Support & platform ops",track:"Incidents & recovery",desc:"Contain incidents, preserve tenant context and coordinate governed recovery.",outcomes:["Impact triage","Narrow containment","Recovery evidence"]}
];
const roleCurricula={
  owner:{promise:"Know when the organisation is truly ready—not merely enabled.",modules:[["Own the operating boundary","Learn how entity profile, entitlements, staffing and product scope combine to define what the tenant may do.","Map each readiness dimension to its accountable owner and current evidence."],["Read readiness as a control system","Understand why missing, stale or unverifiable evidence keeps activity restricted and how dependencies affect go-live.","Diagnose a synthetic tenant with one expired provider certification."],["Approve without self-certifying","Separate preparation, review and approval; identify decisions that need an independent actor.","Build a maker-checker route for activation and material change."],["Keep readiness alive","Treat activation as a maintained state across incidents, revocations, product changes and recovery exercises.","Decide whether to pause narrowly, restrict a journey or hold the tenant."]],practice:["Go-live review room","You inherit a tenant marked ‘ready’, but its collections role is vacant and a KYC provider certificate expires tomorrow. Explain what can remain available, what must be restricted and which evidence is needed before approval.","Checkpoint: no production activity is inferred safe from a cosmetic status or incomplete evidence."]},
  product:{promise:"Translate product intent into controlled, testable configuration.",modules:[["Define the product contract","Connect borrower need, facility mechanics, disclosures, accounting and lifecycle behaviour before configuring rules.","Write a boundary statement for one product and identify its authoritative inputs."],["Model policy as governed data","Use versioned decision models and golden cases instead of embedding policy in workflow code.","Classify five proposed rules as product data, decision policy or workflow control."],["Manage effective change","Understand draft, approval, effective date, supersession and the consequences for in-flight applications.","Plan a rate and eligibility change without mutating an effective version."],["Prove journey readiness","Join configuration, providers, roles, documents and tenant UAT into a release decision.","Design positive, adverse and stale-version acceptance cases."]],practice:["Product change workshop","A product team wants to raise the maximum amount today while retaining the old KFS template and existing in-flight decisions. Produce a safe versioning and validation plan.","Checkpoint: an effective policy is never edited in place and configuration does not outrun disclosure or testing."]},
  loan:{promise:"Progress a borrower fairly while preserving every decision boundary.",modules:[["Establish a lawful application","Connect purpose, notice, consent, identity and evidence quality to the application record.","Spot missing provenance in a synthetic borrower file."],["Read the decision, not just the outcome","Interpret verified facts, policy version, reason codes and restrictive results without guessing.","Explain an approve, refer and decline trace to a reviewer."],["Resolve referrals correctly","Correct facts through authorised workflows and distinguish remediation from an override.","Route a referral while preserving the original result and maker-checker separation."],["Close the origination promise","Reconcile sanctioned terms, KFS delivery, acknowledgement and disbursement conditions.","Find the gate that must hold when acknowledgement evidence is absent."]],practice:["First compliant loan case","A salaried borrower passes KYC but receives a referral after an income document mismatch. Resolve the case, explain the evidence trail and determine when KFS generation may begin.","Checkpoint: unavailable evidence or services create a hold or referral, never an assumed approval."]},
  operations:{promise:"Move money and state only when authority and evidence agree.",modules:[["Understand account truth","Separate contractual schedule, actual ledger entries and business status across servicing.","Reconcile a repayment allocation to exact principal, interest, fee and suspense entries."],["Control disbursement","Verify beneficiary, conditions, approval and idempotency before an external effect.","Respond to a timeout where the bank may have moved funds."],["Operate servicing changes","Handle mandates, reschedules, corrections and borrower requests without rewriting history.","Design the evidence for a governed repayment-date change."],["Manage distress and closure","Connect DPD, collections conduct, restructure, settlement, reporting and release obligations.","Determine why a zero balance alone is insufficient for closure."]],practice:["Ambiguous payment exercise","A repayment callback times out and a retry arrives with the same key but different content. Decide what is posted, what is held and how reconciliation proceeds.","Checkpoint: ambiguous external effects go to controlled reconciliation; they are never guessed or duplicated."]},
  compliance:{promise:"Turn obligations into evidence that can withstand review.",modules:[["Trace obligation to control","Move from regulatory family to platform control, operating procedure and evidence without overstating maturity.","Build a trace for one KFS obligation from rule to record."],["Test design and operation","Distinguish whether a control exists from whether it operated effectively for the selected period.","Choose a population, sample and exception rule for a control test."],["Investigate control gaps","Assess impact, preserve facts and drive remediation without editing the historical record.","Triage a missed acknowledgement gate across affected applications."],["Produce scoped assurance","Apply tenant, purpose, period and field restrictions to evidence exports and custody.","Draft an evidence request that is reviewable without oversharing borrower data."]],practice:["Control assurance review","An auditor asks for proof that every sanctioned digital loan received the correct KFS last quarter. Define the population, evidence joins, exceptions and limitations of the conclusion.","Checkpoint: explanatory content and successful samples do not themselves establish production readiness or universal effectiveness."]},
  risk:{promise:"Govern restrictive and exceptional credit outcomes with clear lineage.",modules:[["Frame credit policy","Separate risk appetite, eligibility, affordability and product limits while retaining exact inputs.","Turn an appetite statement into testable decision cases."],["Interpret deterministic decisions","Read facts, provenance, bundle version, reason codes and replay evidence.","Reconstruct why two similar applications received different outcomes."],["Control referrals and overrides","Define permitted discretion, required rationale, authority limits and independent approval.","Reject a proposed override that lacks policy authority or evidence."],["Govern models and change","Understand material model influence, kill-switch degradation, monitoring and release independence.","Respond when a model dependency becomes unavailable during evaluation."]],practice:["Credit committee simulation","A high-value application falls outside one policy threshold but has a strong model score. Decide whether it can progress, what authority is needed and what evidence must survive replay.","Checkpoint: model output never erases deterministic policy, missing facts or independent human authority."]},
  integration:{promise:"Make external dependencies predictable, attributable and safe to fail.",modules:[["Define the provider boundary","Map contract, data purpose, credentials, operations contacts and tenant-specific authority.","Create a certification inventory for one KYC provider."],["Authenticate every effect","Understand request signing, callback verification, replay defence and credential rotation.","Classify valid, duplicate, stale and malformed callbacks."],["Design for uncertain outcomes","Use idempotency, status enquiry and reconciliation when timeout does not reveal whether an effect occurred.","Resolve an ambiguous disbursement without issuing a second payment."],["Promote and monitor safely","Join sandbox evidence, adverse tests, approval, live binding and expiry monitoring.","Decide what must happen when certification expires mid-journey."]],practice:["Provider certification lab","A provider passes happy-path tests but returns success for a replayed callback and cannot demonstrate credential rotation. Make the live-use decision and specify remediation evidence.","Checkpoint: an unavailable or uncertified provider cannot silently create a positive business fact."]},
  support:{promise:"Restore safe service without weakening the controls that protect it.",modules:[["Triage with tenant context","Establish scope, affected journey, time window, control impact and severity before acting.","Build a concise incident statement from noisy operator reports."],["Contain narrowly","Choose the smallest authorised pause while preserving tenant isolation and restrictive defaults.","Compare journey pause, provider disablement and tenant restriction."],["Preserve operational evidence","Keep actor actions, logs, versions, ambiguous effects and communications joined to the incident.","Create a recovery timeline that another reviewer can reproduce."],["Recover and learn","Validate service health, reconcile side effects, obtain authority to resume and turn findings into durable controls.","Define exit criteria for an incident involving payment callbacks."]],practice:["Recovery tabletop","A shared provider is failing for one tenant during disbursement. Contain impact without cross-tenant changes, preserve uncertain effects and define the evidence required to resume.","Checkpoint: throughput pressure never justifies bypassing validation, attribution or tenant isolation."]}
};
const articles=[
  {id:"activate-tenant",category:"Get started",roles:["owner"],title:"Activate a tenant safely",summary:"Complete the eight readiness dimensions before any production activity.",time:"12 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"Sandbox first",control:"Approval required",sections:[
    ["Before you begin","You need an admitted organisation, a verified tenant owner and the approved onboarding blueprint. Do not use production borrower data during initial validation."],
    ["Complete activation","1. Confirm the regulated-entity profile and grievance details.\n2. Approve the initial product policy and its effective date.\n3. Enable only entitled modules and flows.\n4. Assign the required operating and control roles.\n5. Certify integrations or retain approved sandbox mocks.\n6. Complete security, recovery and service readiness evidence."],
    ["Verify the outcome","Activation succeeds only when every required dimension is current. A missing, expired or failed dimension keeps the tenant restricted."],
    ["Control note","Activation is not a cosmetic status change. It is a governed decision with recorded evidence and must fail closed when evidence cannot be verified."]]},
  {id:"first-compliant-loan",category:"Origination",roles:["loan","operations","compliance"],title:"Trace the first compliant loan",summary:"Validate consent, KYC, underwriting, KFS, sanction and servicing as one governed journey.",time:"35 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"Sandbox",control:"Audit evidence",sections:[
    ["Learning objective","Complete one synthetic application end to end and explain the evidence created at each control point."],
    ["Run the journey","1. Create a synthetic borrower and capture purpose-bound consent.\n2. Complete the configured KYC evidence requirements.\n3. Submit verified facts to the eligibility decision.\n4. Resolve a referral without bypassing maker-checker controls.\n5. Generate and acknowledge the Key Facts Statement.\n6. Record sanction conditions and verify disbursement readiness.\n7. Confirm the account appears in servicing."],
    ["Expected evidence","The audit record should connect the actor, tenant, policy version, input facts, decision result, KFS and subsequent loan state changes."],
    ["Production boundary","Passing this sandbox exercise is required onboarding evidence, but does not by itself make a tenant or product journey production-ready."]]},
  {id:"configure-product",category:"Configuration",roles:["product","risk"],title:"Configure a lending product",summary:"Create an effective-dated product policy without scattering lending rules through workflows.",time:"18 min",verified:"14 Jul 2026",availability:"Configurable pattern",environment:"Sandbox first",control:"Maker-checker",sections:[["Plan the policy","Start with the approved product blueprint, currency, amount and tenor bounds, pricing, cooling-off and eligibility requirements."],["Configure and review","Create a new effective-dated version, validate it against the golden corpus and submit it for independent approval. Never edit an already-effective policy in place."],["Activate","Bind the approved version to the regulated entity and journey. Run tenant UAT before production activation."],["Control note","Lending policy is decision-model data. Runtime code must not become an alternative policy source."]]},
  {id:"resolve-referral",category:"Origination",roles:["loan","risk"],title:"Resolve a referred decision",summary:"Investigate a restrictive outcome while preserving decision lineage and approval boundaries.",time:"9 min",verified:"13 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Approval required",sections:[["Understand the result","A referral is a restrictive outcome, not a system failure. Review the reason codes, missing evidence and policy version."],["Resolve","Correct inaccurate facts through the authorised workflow, attach required evidence and resubmit. Use an override only when policy permits and the required approver is independent."],["Do not bypass","Never change decision inputs outside the recorded workflow or treat an unavailable decision service as approval."],["Expected evidence","The record must retain the original decision, subsequent facts, actor attribution and final outcome."]]},
  {id:"generate-kfs",category:"Origination",roles:["loan","compliance"],title:"Generate and acknowledge a KFS",summary:"Produce the borrower-facing Key Facts Statement with language and acknowledgement evidence.",time:"11 min",verified:"12 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Regulatory control",sections:[["Prerequisites","The sanctioned terms, APR components, charges, cooling-off terms and borrower language choice must be complete."],["Generate","Generate the KFS from the approved terms. Review that figures reconcile and deliver it through the approved channel."],["Acknowledge","Capture delivery and acknowledgement evidence before moving through the configured downstream gate."],["Exception handling","If generation, delivery or acknowledgement evidence is missing, stop the journey and resolve the exception. Do not substitute an informal document."]]},
  {id:"evidence-pack",category:"Assurance",roles:["compliance","owner","support"],title:"Export an integrity-attested evidence pack",summary:"Demonstrate the audit chain and assemble review-ready evidence for an authorised request.",time:"15 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Sensitive export",sections:[["Define the request","Confirm the authorised requester, tenant, purpose, date range and exact control or journey scope."],["Generate","Export only the scoped records and their integrity material. Keep tenant evidence isolated and preserve field-level restrictions."],["Verify integrity","Use the provided verification result to confirm the audit sequence and external anchor evidence where configured."],["Custody","Record who generated, received and retained the pack. Follow legal hold and deletion requirements; an export is not permission for indefinite retention."]]},
  {id:"provider-readiness",category:"Integrations",roles:["integration","owner"],title:"Certify a provider for live use",summary:"Move an integration from sandbox to live only after contractual, security and operational evidence is current.",time:"20 min",verified:"11 Jul 2026",availability:"Configurable pattern",environment:"Sandbox first",control:"Go-live gate",sections:[["Collect evidence","Confirm contract, data residency, security, callback authentication, service limits, incident contacts and regulatory applicability."],["Test","Run positive, negative, timeout, replay and malformed-callback scenarios in the tenant sandbox."],["Approve","Record independent approval and bind the certified provider version to the exact tenant and journey."],["Fail closed","An unavailable, expired or uncertified provider must not silently produce a successful business outcome."]]},
  {id:"incident-response",category:"Operations",roles:["support","owner"],title:"Start an operational incident",summary:"Contain impact, preserve evidence and reach the correct service owner without losing tenant context.",time:"8 min",verified:"10 Jul 2026",availability:"Controlled first slice",environment:"Production",control:"Incident record",sections:[["Triage","Identify the tenant, affected journey, time window, user impact and whether a security or regulatory control is involved."],["Contain","Pause the narrowest affected capability using authorised controls. Do not weaken validation or tenant isolation to restore throughput."],["Escalate","Notify the service owner and the tenant contact according to severity and contractual timelines."],["Preserve evidence","Keep actor attribution, logs, policy versions and recovery actions linked to the incident record."]]}
];
const filters=["All","Get started","Origination","Configuration","Assurance","Integrations","Operations"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function articleCard(a){return `<button class="article-card" data-open="${a.id}"><div class="tags"><span class="tag">${a.category}</span><span class="tag ${a.environment.includes("Sandbox")?"sandbox":""}">${a.environment}</span></div><h3>${a.title}</h3><p>${a.summary}</p><footer><span>${a.time}</span><span>Verified ${a.verified}</span></footer></button>`}
function renderHome(){
  $("#role-grid").innerHTML=roles.map((r,i)=>{const guides=articles.filter(a=>a.roles.includes(r.id));const minutes=guides.reduce((sum,a)=>sum+Number.parseInt(a.time,10),0);return `<button class="role-card" data-role="${r.id}"><span class="role-number">${String(i+1).padStart(2,"0")}</span><span class="role-icon">${r.icon}</span><span class="role-track">${r.track}</span><h3>${r.name}</h3><p>${r.desc}</p><ul>${r.outcomes.map(outcome=>`<li>${outcome}</li>`).join("")}</ul><span class="role-meta"><b>${guides.length} verified guide${guides.length===1?"":"s"}</b><span>${minutes} min</span></span><span class="role-action">Explore this path <b aria-hidden="true">→</b></span></button>`}).join("");
  $("#filters").innerHTML=filters.map((f,i)=>`<button class="filter ${i===0?"active":""}" data-filter="${f}">${f}</button>`).join("");
  renderArticles(articles.slice(0,6),$("#article-grid"));
}
function renderArticles(items,target){target.innerHTML=items.length?items.map(articleCard).join(""):`<p>No verified guidance matches this search.</p>`}
let currentRoleId=null,currentArticleSourceRole=null;
function routeHash(view,detail={}){if(view==="role")return `#role/${detail.roleId}`;if(view==="article")return `#guide/${detail.articleId}`;if(view==="academy")return "#learning";if(view==="results")return "#guidance";return "#explore"}
function show(view,detail={},historyMode="push"){$$('[id$="-view"]').forEach(v=>v.hidden=true);$(`#${view}-view`).hidden=false;$$('.nav-link[data-view]').forEach(x=>x.classList.toggle("active",x.dataset.view===(view==="academy"?"academy":"home")));window.scrollTo({top:0,behavior:"auto"});const state={view,...detail,from:historyMode==="push"?history.state?.view||null:null};if(historyMode==="push")history.pushState(state,"",routeHash(view,detail));if(historyMode==="replace")history.replaceState(state,"",routeHash(view,detail))}
function openResults(title,items,historyMode="push"){const ids=items.map(a=>a.id);$("#results-title").textContent=title;$("#results-count").textContent=`${items.length} verified guide${items.length===1?"":"s"}`;renderArticles(items,$("#results-grid"));show("results",{title,ids},historyMode)}
function openRole(id,historyMode="push"){const role=roles.find(r=>r.id===id),course=roleCurricula[id];if(!role||!course)return;currentRoleId=id;const guides=articles.filter(a=>a.roles.includes(id));const minutes=guides.reduce((sum,a)=>sum+Number.parseInt(a.time,10),0);$("#role-track").textContent=role.track;$("#role-title").textContent=role.name;$("#role-intro").textContent=role.desc+" This path develops the judgement behind the task, then connects it to operating guidance.";$("#role-monogram").textContent=role.icon;$("#role-promise").textContent=course.promise;$("#role-stats").innerHTML=`<span>4 learning modules</span><span>1 applied case</span><span>${guides.length} verified guides · ${minutes} min</span>`;$("#role-modules").innerHTML=course.modules.map(([title,body,application],i)=>`<article class="path-module" aria-labelledby="${id}-module-${i+1}"><div><span class="module-position">Module ${i+1} of ${course.modules.length}</span><h3 id="${id}-module-${i+1}">${title}</h3><p>${body}</p></div><div class="module-application"><span>Apply the judgement</span><p>${application}</p></div></article>`).join("");$("#role-practice").innerHTML=`<div><p class="eyebrow">Applied case</p><h2>${course.practice[0]}</h2></div><div><p>${course.practice[1]}</p><p class="practice-checkpoint">${course.practice[2]}</p></div>`;renderArticles(guides,$("#role-guides"));show("role",{roleId:id},historyMode)}
function openArticle(id,{sourceRole=null,historyMode="push"}={}){const a=articles.find(x=>x.id===id);if(!a)return;currentArticleSourceRole=sourceRole;const source=roles.find(r=>r.id===sourceRole);$("#article-back").textContent=source?`← Back to ${source.name} path`:"← Back to guidance";$("#article-tags").innerHTML=`<span class="tag">${a.availability}</span><span class="tag sandbox">${a.environment}</span><span class="tag control">${a.control}</span>`;$("#article-title").textContent=a.title;$("#article-summary").textContent=a.summary;$("#article-meta").textContent=`${a.time} · Last verified ${a.verified} · Content scope: LoanOS canonical`;$("#article-toc").innerHTML=a.sections.map(s=>`<li>${s[0]}</li>`).join("");$("#article-body").innerHTML=a.sections.map(([h,b],i)=>`<section><h2>${i+1}. ${h}</h2>${h.includes("Control")||h.includes("boundary")?`<div class="callout">${b}</div>`:`${b.split("\n").length>1?`<ol>${b.split("\n").map(x=>`<li>${x.replace(/^\d+\.\s*/,"")}</li>`).join("")}</ol>`:`<p>${b}</p>`}`}</section>`).join("");show("article",{articleId:id,sourceRole},historyMode)}
function search(q){const text=q.trim().toLowerCase();if(!text)return openResults("All guidance",articles);openResults(`Results for “${q.trim()}”`,articles.filter(a=>[a.title,a.summary,a.category,...a.roles,...a.sections.flat()].join(" ").toLowerCase().includes(text)))}
function renderAcademy(){const courses=`<article class="learning-card"><div class="tags"><span class="tag">Full course</span><span class="tag control">Regulatory + platform</span></div><h2>BA Lending Academy</h2><p>Indian lending end to end — LOS, LMS, LWS, collections and the compliance control plane, with regulatory anchors and platform citations in every lesson.</p><p><strong>15 modules · 78 lessons</strong> · ~18 h</p><a class="primary" href="/help/academy/">Open BA course →</a></article><article class="learning-card"><div class="tags"><span class="tag">Technical deep dive</span><span class="tag sandbox">PRD + code + diagrams</span></div><h2>LoanOS Technical Academy</h2><p>Every plane, runtime, control, API flow and all 21 product journeys—from tenant admission through lending, operations and recovery.</p><p><strong>6 modules · 45 sessions</strong> · ~27 h</p><a class="primary" href="/help/technical-academy/">Open technical course →</a></article>`;const paths=[articles[1],articles[0],articles[5],articles[6]];$("#learning-grid").innerHTML=courses+paths.map((a,i)=>`<article class="learning-card"><div class="tags"><span class="tag">${i===0?"Recommended":"Learning path"}</span><span class="tag sandbox">Sandbox practice</span></div><h2>${a.title}</h2><p>${a.summary}</p><p><strong>${i===0?"6":"3"} lessons</strong> · ${a.time}</p><button class="primary" data-open="${a.id}">Start path →</button></article>`).join("")}

function restoreRoute(state,historyMode="none"){if(!state)return show("home",{},historyMode);if(state.view==="role")return openRole(state.roleId,historyMode);if(state.view==="article")return openArticle(state.articleId,{sourceRole:state.sourceRole,historyMode});if(state.view==="results")return openResults(state.title||"All guidance",articles.filter(a=>(state.ids||[]).includes(a.id)),historyMode);if(state.view==="academy")return show("academy",{},historyMode);show("home",{},historyMode)}
document.addEventListener("click",e=>{const open=e.target.closest("[data-open]");if(open){const sourceRole=open.closest("#role-guides")?currentRoleId:null;openArticle(open.dataset.open,{sourceRole})}const role=e.target.closest("[data-role]");if(role)openRole(role.dataset.role);const filter=e.target.closest("[data-filter]");if(filter){$$('[data-filter]').forEach(x=>x.classList.toggle("active",x===filter));renderArticles(filter.dataset.filter==="All"?articles.slice(0,6):articles.filter(a=>a.category===filter.dataset.filter),$("#article-grid"))}const back=e.target.closest("[data-back]");if(back){if(history.state?.from)history.back();else if(back.dataset.back==="context"&&currentArticleSourceRole)openRole(currentArticleSourceRole,"replace");else show("home",{},"replace")}const scroll=e.target.closest("[data-scroll]");if(scroll)document.getElementById(scroll.dataset.scroll)?.scrollIntoView({behavior:"smooth",block:"start"});const query=e.target.closest("[data-query]");if(query)search(query.dataset.query);const nav=e.target.closest("[data-view]");if(nav)show(nav.dataset.view)});
$("#search-form").addEventListener("submit",e=>{e.preventDefault();search($("#search-input").value)});$("#view-all").addEventListener("click",()=>openResults("All guidance",articles));$("#support-button").addEventListener("click",()=>$("#support-dialog").showModal());$(".dialog-close").addEventListener("click",()=>$("#support-dialog").close());$("#dialog-search").addEventListener("click",()=>{$("#support-dialog").close();show("home");$("#search-input").focus()});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();show("home");$("#search-input").focus()}});window.addEventListener("popstate",e=>restoreRoute(e.state));
renderHome();renderAcademy();
const initialHash=location.hash.match(/^#role\/([^/]+)$/);const initialGuide=location.hash.match(/^#guide\/([^/]+)$/);if(initialHash)openRole(initialHash[1],"replace");else if(initialGuide)openArticle(initialGuide[1],{historyMode:"replace"});else if(location.hash==="#learning")show("academy",{},"replace");else show("home",{},"replace");
