const roles=[
  {id:"owner",icon:"O",name:"Tenant owner",desc:"Activate the organisation, staff roles and prepare for go-live."},
  {id:"product",icon:"P",name:"Product administrator",desc:"Configure products, policies, effective dates and workflows."},
  {id:"loan",icon:"₹",name:"Loan officer",desc:"Process applications from consent through sanction."},
  {id:"operations",icon:"↻",name:"Operations & servicing",desc:"Manage disbursement, repayments, collections and exceptions."},
  {id:"compliance",icon:"✓",name:"Compliance officer",desc:"Assure controls, evidence and regulatory obligations."},
  {id:"risk",icon:"△",name:"Risk & credit manager",desc:"Govern decision policies, referrals and overrides."},
  {id:"integration",icon:"↔",name:"Integration administrator",desc:"Certify providers, credentials and callback operations."},
  {id:"support",icon:"?",name:"Support & platform ops",desc:"Investigate incidents, recovery and service escalation."}
];
const articles=[
  {id:"activate-tenant",category:"Get started",roles:["owner"],title:"Activate a tenant safely",summary:"Complete the eight readiness dimensions before any production activity.",time:"12 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"Sandbox first",control:"Approval required",sections:[
    ["Before you begin","You need an admitted organisation, a verified tenant owner and the approved onboarding blueprint. Do not use production borrower data during initial validation."],
    ["Complete activation","1. Confirm the regulated-entity profile and grievance details.\n2. Approve the initial product policy and its effective date.\n3. Enable only entitled modules and flows.\n4. Assign the required operating and control roles.\n5. Certify integrations or retain approved sandbox mocks.\n6. Complete security, recovery and service readiness evidence."],
    ["Verify the outcome","Activation succeeds only when every required dimension is current. A missing, expired or failed dimension keeps the tenant restricted."],
    ["Control note","Activation is not a cosmetic status change. It is a governed decision with recorded evidence and must fail closed when evidence cannot be verified."]]},
  {id:"first-compliant-loan",category:"Origination",roles:["loan","operations","compliance"],title:"Trace the first compliant loan",summary:"Validate consent, KYC, underwriting, KFS, sanction and servicing as one governed journey.",time:"35 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"Sandbox",control:"Audit evidence",sections:[
    ["Learning objective","Complete one synthetic application end to end and explain the evidence created at each control point."],
    ["Run the journey","1. Create a synthetic borrower and capture purpose-bound consent.\n2. Complete the configured KYC evidence requirements.\n3. Submit verified facts to the eligibility decision.\n4. Resolve a referral without bypassing maker-checker controls.\n5. Generate and acknowledge the Key Facts Statement.\n6. Record sanction conditions and verify disbursement readiness.\n7. Confirm the account appears in servicing."],
    ["Expected evidence","The audit record should connect the actor, tenant, policy version, input facts, decision result, KFS and subsequent loan state changes."],
    ["Production boundary","Passing this sandbox exercise is required onboarding evidence, but does not by itself make a tenant or product journey production-ready."]]},
  {id:"configure-product",category:"Configuration",roles:["product","risk"],title:"Configure a lending product",summary:"Create an effective-dated product policy without scattering lending rules through workflows.",time:"18 min",verified:"14 Jul 2026",availability:"Configurable pattern",environment:"Sandbox first",control:"Maker-checker",sections:[["Plan the policy","Start with the approved product blueprint, currency, amount and tenor bounds, pricing, cooling-off and eligibility requirements."],["Configure and review","Create a new effective-dated version, validate it against the golden corpus and submit it for independent approval. Never edit an already-effective policy in place."],["Activate","Bind the approved version to the regulated entity and journey. Run tenant UAT before production activation."],["Control note","Lending policy is decision-model data. Runtime code must not become an alternative policy source."]]},
  {id:"resolve-referral",category:"Origination",roles:["loan","risk"],title:"Resolve a referred decision",summary:"Investigate a restrictive outcome while preserving decision lineage and approval boundaries.",time:"9 min",verified:"13 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Approval required",sections:[["Understand the result","A referral is a restrictive outcome, not a system failure. Review the reason codes, missing evidence and policy version."],["Resolve","Correct inaccurate facts through the authorised workflow, attach required evidence and resubmit. Use an override only when policy permits and the required approver is independent."],["Do not bypass","Never change decision inputs outside the recorded workflow or treat an unavailable decision service as approval."],["Expected evidence","The record must retain the original decision, subsequent facts, actor attribution and final outcome."]]},
  {id:"generate-kfs",category:"Origination",roles:["loan","compliance"],title:"Generate and acknowledge a KFS",summary:"Produce the borrower-facing Key Facts Statement with language and acknowledgement evidence.",time:"11 min",verified:"12 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Regulatory control",sections:[["Prerequisites","The sanctioned terms, APR components, charges, cooling-off terms and borrower language choice must be complete."],["Generate","Generate the KFS from the approved terms. Review that figures reconcile and deliver it through the approved channel."],["Acknowledge","Capture delivery and acknowledgement evidence before moving through the configured downstream gate."],["Exception handling","If generation, delivery or acknowledgement evidence is missing, stop the journey and resolve the exception. Do not substitute an informal document."]]},
  {id:"evidence-pack",category:"Assurance",roles:["compliance","owner","support"],title:"Export an integrity-attested evidence pack",summary:"Demonstrate the audit chain and assemble review-ready evidence for an authorised request.",time:"15 min",verified:"15 Jul 2026",availability:"Controlled first slice",environment:"All",control:"Sensitive export",sections:[["Define the request","Confirm the authorised requester, tenant, purpose, date range and exact control or journey scope."],["Generate","Export only the scoped records and their integrity material. Keep tenant evidence isolated and preserve field-level restrictions."],["Verify integrity","Use the provided verification result to confirm the audit sequence and external anchor evidence where configured."],["Custody","Record who generated, received and retained the pack. Follow legal hold and deletion requirements; an export is not permission for indefinite retention."]]},
  {id:"provider-readiness",category:"Integrations",roles:["integration","owner"],title:"Certify a provider for live use",summary:"Move an integration from sandbox to live only after contractual, security and operational evidence is current.",time:"20 min",verified:"11 Jul 2026",availability:"Configurable pattern",environment:"Sandbox first",control:"Go-live gate",sections:[["Collect evidence","Confirm contract, data residency, security, callback authentication, service limits, incident contacts and regulatory applicability."],["Test","Run positive, negative, timeout, replay and malformed-callback scenarios in the tenant sandbox."],["Approve","Record independent approval and bind the certified provider version to the exact tenant and journey."],["Fail closed","An unavailable, expired or uncertified provider must not silently produce a successful business outcome."]]},
  {id:"incident-response",category:"Operations",roles:["support","owner"],title:"Start an operational incident",summary:"Contain impact, preserve evidence and reach the correct service owner without losing tenant context.",time:"8 min",verified:"10 Jul 2026",availability:"Controlled first slice",environment:"Production",control:"Incident record",sections:[["Triage","Identify the tenant, affected journey, time window, user impact and whether a security or regulatory control is involved."],["Contain","Pause the narrowest affected capability using authorised controls. Do not weaken validation or tenant isolation to restore throughput."],["Escalate","Notify the service owner and the tenant contact according to severity and contractual timelines."],["Preserve evidence","Keep actor attribution, logs, policy versions and recovery actions linked to the incident record."]]}
];
const filters=["All","Get started","Origination","Configuration","Assurance","Integrations","Operations"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function articleCard(a){return `<button class="article-card" data-open="${a.id}"><div class="tags"><span class="tag">${a.category}</span><span class="tag ${a.environment.includes("Sandbox")?"sandbox":""}">${a.environment}</span></div><h3>${a.title}</h3><p>${a.summary}</p><footer><span>${a.time}</span><span>Verified ${a.verified}</span></footer></button>`}
function renderHome(){
  $("#role-grid").innerHTML=roles.map(r=>`<button class="role-card" data-role="${r.id}"><span class="role-icon">${r.icon}</span><h3>${r.name}</h3><p>${r.desc}</p></button>`).join("");
  $("#filters").innerHTML=filters.map((f,i)=>`<button class="filter ${i===0?"active":""}" data-filter="${f}">${f}</button>`).join("");
  renderArticles(articles.slice(0,6),$("#article-grid"));
}
function renderArticles(items,target){target.innerHTML=items.length?items.map(articleCard).join(""):`<p>No verified guidance matches this search.</p>`}
function show(view){$$('[id$="-view"]').forEach(v=>v.hidden=true);$(`#${view}-view`).hidden=false;scrollTo({top:0,behavior:"smooth"})}
function openResults(title,items){$("#results-title").textContent=title;$("#results-count").textContent=`${items.length} verified guide${items.length===1?"":"s"}`;renderArticles(items,$("#results-grid"));show("results")}
function openArticle(id){const a=articles.find(x=>x.id===id);if(!a)return;$("#article-tags").innerHTML=`<span class="tag">${a.availability}</span><span class="tag sandbox">${a.environment}</span><span class="tag control">${a.control}</span>`;$("#article-title").textContent=a.title;$("#article-summary").textContent=a.summary;$("#article-meta").textContent=`${a.time} · Last verified ${a.verified} · Content scope: LoanOS canonical`;$("#article-toc").innerHTML=a.sections.map(s=>`<li>${s[0]}</li>`).join("");$("#article-body").innerHTML=a.sections.map(([h,b],i)=>`<section><h2>${i+1}. ${h}</h2>${h.includes("Control")||h.includes("boundary")?`<div class="callout">${b}</div>`:`${b.split("\n").length>1?`<ol>${b.split("\n").map(x=>`<li>${x.replace(/^\d+\.\s*/,"")}</li>`).join("")}</ol>`:`<p>${b}</p>`}`}</section>`).join("");show("article")}
function search(q){const text=q.trim().toLowerCase();if(!text)return openResults("All guidance",articles);openResults(`Results for “${q.trim()}”`,articles.filter(a=>[a.title,a.summary,a.category,...a.roles,...a.sections.flat()].join(" ").toLowerCase().includes(text)))}
function renderAcademy(){const courses=`<article class="learning-card"><div class="tags"><span class="tag">Full course</span><span class="tag control">Regulatory + platform</span></div><h2>BA Lending Academy</h2><p>Indian lending end to end — LOS, LMS, LWS, collections and the compliance control plane, with regulatory anchors and platform citations in every lesson.</p><p><strong>11 modules · 57 lessons</strong> · ~14 h</p><a class="primary" href="/help/academy/">Open BA course →</a></article><article class="learning-card"><div class="tags"><span class="tag">Technical deep dive</span><span class="tag sandbox">PRD + code + diagrams</span></div><h2>LoanOS Technical Academy</h2><p>Every plane, runtime, control, API flow and all 21 product journeys—from tenant admission through lending, operations and recovery.</p><p><strong>6 modules · 45 sessions</strong> · ~27 h</p><a class="primary" href="/help/technical-academy/">Open technical course →</a></article>`;const paths=[articles[1],articles[0],articles[5],articles[6]];$("#learning-grid").innerHTML=courses+paths.map((a,i)=>`<article class="learning-card"><div class="tags"><span class="tag">${i===0?"Recommended":"Learning path"}</span><span class="tag sandbox">Sandbox practice</span></div><h2>${a.title}</h2><p>${a.summary}</p><p><strong>${i===0?"6":"3"} lessons</strong> · ${a.time}</p><button class="primary" data-open="${a.id}">Start path →</button></article>`).join("")}

document.addEventListener("click",e=>{const open=e.target.closest("[data-open]");if(open)openArticle(open.dataset.open);const role=e.target.closest("[data-role]");if(role){const r=roles.find(x=>x.id===role.dataset.role);openResults(`Guidance for ${r.name}`,articles.filter(a=>a.roles.includes(r.id)))}const filter=e.target.closest("[data-filter]");if(filter){$$('[data-filter]').forEach(x=>x.classList.toggle("active",x===filter));renderArticles(filter.dataset.filter==="All"?articles.slice(0,6):articles.filter(a=>a.category===filter.dataset.filter),$("#article-grid"))}if(e.target.closest("[data-back]"))show("home");const query=e.target.closest("[data-query]");if(query)search(query.dataset.query);const nav=e.target.closest("[data-view]");if(nav){show(nav.dataset.view);$$('.nav-link').forEach(x=>x.classList.toggle("active",x===nav))}});
$("#search-form").addEventListener("submit",e=>{e.preventDefault();search($("#search-input").value)});$("#view-all").addEventListener("click",()=>openResults("All guidance",articles));$("#support-button").addEventListener("click",()=>$("#support-dialog").showModal());$(".dialog-close").addEventListener("click",()=>$("#support-dialog").close());$("#dialog-search").addEventListener("click",()=>{$("#support-dialog").close();show("home");$("#search-input").focus()});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();show("home");$("#search-input").focus()}});
renderHome();renderAcademy();
