import test from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readFile, access } from "node:fs/promises";

const run = promisify(execFile);
const root = new URL("..", import.meta.url);
const academy = new URL("../apps/help/academy/", import.meta.url);
const { course, glossary } = await import(new URL("content/course.mjs", academy).href);

test("BA academy curriculum satisfies its content contract", async () => {
  const register = await readFile(new URL("docs/compliance/india-regulatory-register.md", root), "utf8");
  const catalog = await readFile(new URL("docs/product/complete-system-capability-catalog.md", root), "utf8");
  const guides = await readFile(new URL("apps/help/help.js", root), "utf8");
  const guideIds = new Set([...guides.matchAll(/id:"([a-z0-9-]+)"/g)].map((m) => m[1]));
  const registerIds = new Set([...register.matchAll(/^\|\s*([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\s*\|/gm)].map((m) => m[1]));
  const glossaryTerms = new Set(glossary.map((entry) => entry.term));
  const lessonPaths = new Set(course.modules.flatMap((m) => m.lessons.map((l) => `${m.id}/${l.id}`)));

  assert.equal(course.modules.length, 15);
  assert.equal(course.modules.reduce((total, module) => total + module.lessons.length, 0), 78);
  assert.ok(course.disclaimer.includes("not legal advice"));

  const { PRODUCT_JOURNEY_CONTRACTS } = await import("@loanos/core/journeys/product-journey-contracts.js");
  const journeysModule = course.modules.find((module) => module.id === "journeys");
  assert.equal(journeysModule.lessons.length, 21, "one deep-dive lesson per canonical journey");
  const covered = new Set(journeysModule.lessons.map((lesson) => lesson.journeyType));
  for (const journeyType of Object.keys(PRODUCT_JOURNEY_CONTRACTS)) assert.ok(covered.has(journeyType), `journey ${journeyType} has a deep-dive lesson`);
  for (const requiredModule of ["m10-product-customer", "m11-lending-terms", "m12-collateral", "m13-ba-practice"])
    assert.ok(course.modules.some((module) => module.id === requiredModule), `complete BA coverage includes ${requiredModule}`);
  for (const module of course.modules) {
    for (const lesson of module.lessons) {
      const where = `${module.id}/${lesson.id}`;
      assert.ok(lesson.verified, `${where} carries a verification date`);
      assert.ok(lesson.regulatory.length >= 1, `${where} cites a regulatory anchor`);
      for (const anchor of lesson.regulatory) assert.ok(registerIds.has(anchor.id), `${where}: ${anchor.id} exists in the regulatory register`);
      assert.ok(lesson.platform.length >= 1, `${where} cites the platform`);
      for (const citation of lesson.platform) {
        if (citation.type === "capability") assert.ok(catalog.includes(`| ${citation.ref} |`), `${where}: capability ${citation.ref} exists in the catalogue`);
        if (citation.type === "guide") assert.ok(guideIds.has(citation.ref), `${where}: guide ${citation.ref} exists`);
        if (citation.type === "doc" || citation.type === "code") await access(new URL(citation.ref, root));
      }
      for (const term of lesson.terms ?? []) assert.ok(glossaryTerms.has(term), `${where}: term "${term}" is in the glossary`);
      for (const target of lesson.related ?? []) assert.ok(lessonPaths.has(target), `${where}: related link ${target} resolves`);
      assert.ok(lesson.check.length >= 1, `${where} has a knowledge check`);
      for (const question of lesson.check) assert.ok(question.answer >= 0 && question.answer < question.options.length, `${where}: answer index valid`);
    }
  }
});

test("generated academy pages are current and correctly linked", async () => {
  await run("node", ["scripts/build-academy.mjs", "--check"], { cwd: root });

  const home = await readFile(new URL("index.html", academy), "utf8");
  assert.match(home, /BA Lending Academy/);
  assert.match(home, /generated by scripts\/build-academy\.mjs/i);
  assert.match(home, /class="hero-visual"/);
  assert.match(home, /class="module-card-visual"/);
  assert.match(home, /loading="lazy"/);
  assert.doesNotMatch(home, /localStorage|sessionStorage|indexedDB/);

  const firstModule = course.modules[0];
  const firstLesson = firstModule.lessons[0];
  const lessonHtml = await readFile(new URL(`${firstModule.id}/${firstLesson.id}.html`, academy), "utf8");
  assert.match(lessonHtml, /Regulatory anchors/);
  assert.match(lessonHtml, /Where this lives in LoanOS/);
  assert.match(lessonHtml, /Knowledge check/);
  assert.match(lessonHtml, /href="\/help\/academy\/glossary\.html/);
  assert.match(lessonHtml, /class="lesson-visual"/);
  assert.match(lessonHtml, /alt="[^"]+"/);

  for (const module of course.modules) {
    await access(new URL(`${module.id}/index.html`, academy));
    for (const lesson of module.lessons) await access(new URL(`${module.id}/${lesson.id}.html`, academy));
  }

  const goldLoan = await readFile(new URL("journeys/gold-loan.html", academy), "utf8");
  assert.match(goldLoan, /Journey contract/, "journey lessons carry the derived contract panel");
  assert.match(goldLoan, /gold_pledge/, "security type derives from the product contract");
  assert.match(goldLoan, /Platform support/, "journey lessons carry the support-matrix panel");
  assert.match(goldLoan, /product-journey\/gold_loan/, "contract id and checksum are cited");
});

test("guide surfaces link to the BA academy", async () => {
  const [html, js] = await Promise.all([
    readFile(new URL("apps/help/index.html", root), "utf8"),
    readFile(new URL("apps/help/help.js", root), "utf8")
  ]);
  assert.match(html, /\/help\/academy\//);
  assert.match(js, /\/help\/academy\//);
});
