import test from "node:test"; import assert from "node:assert/strict";
import { createCommunicationDelivery, projectCommunicationDeliveryReconciliation, recordCommunicationCallback, signCommunicationCallback } from "../packages/core/src/communication-delivery-lifecycle.js";
const NOW=new Date("2026-07-15T00:00:00Z"),SECRET="secret",tenantId="tenant-1";
function callback(eventId,payload,at=NOW){const rawBody=JSON.stringify(payload),timestamp=at.toISOString(),provider="provider_a";return{provider,eventId,timestamp,rawBody,signature:signCommunicationCallback({provider,eventId,timestamp,rawBody},SECRET)};}
function delivery(channel="sms"){return createCommunicationDelivery({}, {tenantId,deliveryId:"d1",channel,recipientRef:"recipient/1",templateId:"payment_reminder",templateVersion:"1",dltTemplateId:channel==="sms"?"dlt-1":undefined,dltEntityId:channel==="sms"?"entity-1":undefined,idempotencyKey:"idem-1"},NOW);}
test("creation is tenant scoped and idempotency conflicts fail closed",()=>{const r=delivery();assert.equal(createCommunicationDelivery(r.registry,{...r.delivery},NOW).idempotent,true);assert.throws(()=>createCommunicationDelivery(r.registry,{tenantId,deliveryId:"d2",channel:"sms",recipientRef:"other",templateId:"t",templateVersion:"1",dltTemplateId:"d",dltEntityId:"e",idempotencyKey:"idem-1"},NOW),e=>e.code==="communication_delivery_idempotency_conflict");});
test("signed callbacks enforce transitions, tenant scope and duplicate event identity",()=>{let r=delivery();const submitted=callback("e1",{deliveryId:"d1",status:"submitted",providerMessageId:"pm1"});assert.throws(()=>recordCommunicationCallback(r.registry,submitted,"bad",{tenantId},NOW),e=>e.code==="communication_callback_signature_invalid");assert.throws(()=>recordCommunicationCallback(r.registry,submitted,SECRET,{tenantId:"other"},NOW),e=>e.code==="communication_delivery_tenant_mismatch");r=recordCommunicationCallback(r.registry,submitted,SECRET,{tenantId},NOW);assert.equal(r.delivery.status,"submitted");assert.equal(recordCommunicationCallback(r.registry,submitted,SECRET,{tenantId},NOW).idempotent,true);r=recordCommunicationCallback(r.registry,callback("e2",{deliveryId:"d1",status:"delivered",occurredAt:NOW.toISOString()}),SECRET,{tenantId},NOW);assert.equal(r.delivery.status,"delivered");assert.throws(()=>recordCommunicationCallback(r.registry,callback("e3",{deliveryId:"d1",status:"failed",failureCode:"X"}),SECRET,{tenantId},NOW),e=>e.code==="communication_delivery_transition_invalid");});
test("channel statuses and DLT/template failures are validated",()=>{let sms=delivery();sms=recordCommunicationCallback(sms.registry,callback("s1",{deliveryId:"d1",status:"submitted",providerMessageId:"pm"}),SECRET,{tenantId},NOW);sms=recordCommunicationCallback(sms.registry,callback("s2",{deliveryId:"d1",status:"failed",failureCode:"DLT_REJECTED",failureReason:"Template not registered"}),SECRET,{tenantId},NOW);assert.equal(sms.delivery.failureCode,"DLT_REJECTED");let email=delivery("email");email=recordCommunicationCallback(email.registry,callback("m1",{deliveryId:"d1",status:"submitted",providerMessageId:"pm"}),SECRET,{tenantId},NOW);email=recordCommunicationCallback(email.registry,callback("m2",{deliveryId:"d1",status:"bounced",failureCode:"MAILBOX",failureReason:"Mailbox unavailable"}),SECRET,{tenantId},NOW);assert.equal(email.delivery.status,"bounced");assert.throws(()=>recordCommunicationCallback(email.registry,callback("m3",{deliveryId:"d1",status:"opted_out"}),SECRET,{tenantId},NOW),e=>e.code==="communication_delivery_transition_invalid");});
test("reconciliation projection exposes unresolved and provider correlation exceptions",()=>{let r=delivery();let p=projectCommunicationDeliveryReconciliation(r.registry,{tenantId});assert.equal(p.status,"exceptions");r=recordCommunicationCallback(r.registry,callback("e1",{deliveryId:"d1",status:"submitted",providerMessageId:"pm"}),SECRET,{tenantId},NOW);r=recordCommunicationCallback(r.registry,callback("e2",{deliveryId:"d1",status:"delivered"}),SECRET,{tenantId},NOW);p=projectCommunicationDeliveryReconciliation(r.registry,{tenantId});assert.equal(p.status,"reconciled");assert.equal(p.counts.delivered,1);assert.match(p.projectionChecksumSha256,/^[a-f0-9]{64}$/);});
