import test from "node:test"; import assert from "node:assert/strict"; import { mkdtemp, rm } from "node:fs/promises"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { createLoanOsServer } from "../apps/api/src/server.js"; import { signCommunicationCallback } from "@loanos/core/integrations/communication-delivery-lifecycle.js";
const tenant={tenantId:"tenant-comms",name:"Comms Bank",apiKey:"comms-key"}, secret="callback-secret";
async function request(base,path,{method="GET",body,key=tenant.apiKey}={}){return fetch(base+path,{method,headers:{"x-api-key":key,"content-type":"application/json"},body:body?JSON.stringify(body):undefined});}
test("communication dispatch persists lifecycle, signed callbacks and reconciliation with tenant isolation",async t=>{const dataDir=await mkdtemp(join(tmpdir(),"loanos-comms-lifecycle-"));const server=createLoanOsServer({dataDir,bootstrapTenants:[tenant,{tenantId:"other",name:"Other",apiKey:"other-key"}]});await new Promise(r=>server.listen(0,"127.0.0.1",r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;
  const sent=await request(base,"/integrations/communications",{method:"POST",body:{communicationId:"comm-1",idempotencyKey:"idem-1",channel:"email",to:"private@example.in",subject:"Statement",message:"Ready",borrowerId:"b1",templateId:"statement",templateVersion:"2"}});assert.equal(sent.status,201,await sent.clone().text());const created=await sent.json();assert.equal(created.delivery.status,"submitted");assert.equal(created.delivery.recipientRef,"b1");assert.equal(JSON.stringify(created.delivery).includes("private@example.in"),false);
  process.env.LOANOS_PROVIDER_CALLBACK_SECRETS=JSON.stringify({mock:secret});t.after(()=>delete process.env.LOANOS_PROVIDER_CALLBACK_SECRETS);const payload={deliveryId:"comm-1",status:"delivered",occurredAt:new Date().toISOString()},rawBody=JSON.stringify(payload),timestamp=new Date().toISOString(),eventId="provider-event-1",provider="mock",signature=signCommunicationCallback({provider,eventId,timestamp,rawBody},secret);let response=await request(base,"/integrations/communications/callbacks/mock",{method:"POST",body:{eventId,timestamp,signature,payload}});assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json()).delivery.status,"delivered");
  response=await request(base,"/integrations/communications/callbacks/mock",{method:"POST",body:{eventId,timestamp,signature,payload}});assert.equal((await response.json()).idempotent,true);response=await request(base,"/integrations/communications/reconciliation");const projection=await response.json();assert.equal(projection.status,"reconciled");assert.equal(projection.counts.delivered,1);const other=await request(base,"/integrations/communications/reconciliation",{key:"other-key"});assert.equal((await other.json()).total,0);
  const events=await request(base,"/audit/events?type=integration.communication.delivered");assert.equal((await events.json()).count,1);
});
