import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  buildCustomer360,
  assessPartnerCommission,
  createChannelLead,
  createCustomerMergePlan,
  createSuccessionCase,
  recordCustomerPreferences,
  registerChannelPartner,
  registerCustomerRelationship,
  registerPartnerCommissionPolicy,
  transitionChannelLead,
  transitionPartnerCommission,
  transitionSuccessionCase
} from "../packages/core/src/index.js";
import { createLoanOsServer } from "../apps/api/src/server.js";
import { projectChannelOperations } from "../apps/api/src/routes/customer-channel-controls.js";
import { upsertTenantUser } from "../apps/api/src/identity.js";

const NOW = new Date("2026-07-14T00:00:00.000Z"); const approval = { proposedBy: "channel_maker", approvedBy: "channel_checker", approvalRef: "approval-1" };
function baseState() { return { institutionOperatingUnits: { branch1: { unitId: "branch1", status: "active", serviceablePostalCodes: ["400001"] } }, lendingProgrammes: { programme1: { programmeId: "programme1", name: "Personal loan", status: "active", channels: ["branch", "dsa", "digital"], productPolicyIds: ["p1"], operatingUnitIds: ["branch1"] } }, lendingServiceProviders: {}, borrowerProfiles: { b1: { borrowerId: "b1", fullName: "Asha", contact: { email: "asha@example.in", mobile: "9876543210" } }, b2: { borrowerId: "b2", fullName: "Ravi", contact: { email: "ravi@example.in", mobile: "9876543211" } } }, channelPartners: {} }; }
function partner(state = baseState()) { return registerChannelPartner({}, state, { partnerId: "dsa1", partnerType: "dsa", legalName: "Trusted DSA", operatingUnitIds: ["branch1"], programmeIds: ["programme1"], serviceablePostalCodes: ["400001"], contact: { name: "Partner Lead", email: "partner@example.in", mobile: "9876543222" }, agreementRef: "agreement/1", dueDiligenceRef: "dd/1", conductPolicyRef: "conduct/1", consentTrainingRef: "training/1", ...approval }, NOW).partner; }

test("channel partner and commission policy retain conduct, exact economics, and clawback", () => {
  const state = baseState(); const channelPartner = partner(state); const policy = registerPartnerCommissionPolicy({}, { ...state, channelPartners: { [channelPartner.partnerId]: channelPartner } }, { policyId: "commission1", partnerId: channelPartner.partnerId, programmeIds: ["programme1"], basis: "disbursed_amount_bps", rateBps: 125, maximumPayoutPaise: "500000", eligibleEvent: "first_repayment", clawbackDays: 90, taxTreatmentRef: "tax/tds", ...approval }, NOW).policy; assert.equal(policy.rateBps, 125); assert.equal(policy.maximumPayoutPaise, "500000");
});

test("multi-channel lead intake routes serviceability and detects leads and existing customers", () => {
  const state = baseState(); const channelPartner = partner(state); const withPartner = { ...state, channelPartners: { [channelPartner.partnerId]: channelPartner } }; let result = createChannelLead({}, withPartner, { leadId: "lead1", programmeId: "programme1", channel: "dsa", partnerId: "dsa1", postalCode: "400001", contact: { name: "New Customer", email: "new@example.in", mobile: "9876543233" }, requestedAmountPaise: "10000000", requestedProductPolicyId: "p1", attribution: { source: "partner", campaign: "monsoon" }, consentRef: "consent/1", disclosureRef: "disclosure/1", conductAttestationRef: "conduct/lead1", owner: "branch1", createdBy: "partner-agent" }, NOW); assert.equal(result.lead.status, "new"); assert.equal(result.lead.operatingUnitId, "branch1");
  result = createChannelLead(result.registry, withPartner, { leadId: "lead2", programmeId: "programme1", channel: "dsa", partnerId: "dsa1", postalCode: "400001", contact: { name: "Repeat", email: "new@example.in" }, requestedAmountPaise: "5000000", requestedProductPolicyId: "p1", attribution: { source: "partner" }, consentRef: "consent/2", disclosureRef: "disclosure/2", conductAttestationRef: "conduct/lead2", owner: "branch1", createdBy: "partner-agent" }, NOW); assert.equal(result.lead.status, "duplicate_review"); assert.deepEqual(result.lead.duplicateLeadIds, ["lead1"]);
  assert.throws(() => createChannelLead({}, withPartner, { leadId: "blocked", programmeId: "programme1", channel: "dsa", partnerId: "dsa1", postalCode: "400002", contact: { name: "Outside service area", mobile: "9876543244" }, requestedAmountPaise: "5000000", requestedProductPolicyId: "p1", attribution: { source: "partner" }, consentRef: "consent/x", disclosureRef: "disclosure/x", conductAttestationRef: "conduct/x", owner: "branch1", createdBy: "partner-agent" }, NOW), /not authorised/);
  assert.throws(() => createChannelLead({}, withPartner, { leadId: "blocked-product", programmeId: "programme1", channel: "digital", postalCode: "400001", contact: { name: "Wrong product", mobile: "9876543255" }, requestedAmountPaise: "5000000", requestedProductPolicyId: "p2", attribution: { source: "website" }, consentRef: "consent/y", disclosureRef: "disclosure/y", owner: "branch1", createdBy: "system" }, NOW), /not available/);
  const customerMatch = createChannelLead({}, withPartner, { leadId: "lead3", programmeId: "programme1", channel: "digital", postalCode: "400001", contact: { name: "Asha", email: "asha@example.in" }, requestedAmountPaise: "5000000", requestedProductPolicyId: "p1", attribution: { source: "website" }, consentRef: "consent/3", disclosureRef: "disclosure/3", owner: "branch1", createdBy: "system" }, NOW).lead; assert.deepEqual(customerMatch.matchedBorrowerIds, ["b1"]);
});

test("lead lifecycle requires controlled qualification, follow-up, conversion, and abandonment evidence", () => {
  const state = baseState(); const lead = createChannelLead({}, state, { leadId: "lead1", programmeId: "programme1", channel: "digital", postalCode: "400001", contact: { name: "New", email: "new@example.in" }, requestedAmountPaise: "100000", requestedProductPolicyId: "p1", attribution: { source: "website" }, consentRef: "consent", disclosureRef: "disclosure", owner: "branch1", createdBy: "agent" }, NOW).lead; const contacted = transitionChannelLead(lead, { action: "contact", actor: "agent", reason: "welcome call", evidenceRef: "contact/1" }, NOW); const qualified = transitionChannelLead(contacted, { action: "qualify", actor: "agent", reason: "eligible", evidenceRef: "qualification/1" }, NOW); const converted = transitionChannelLead(qualified, { action: "convert", actor: "agent", reason: "application created", evidenceRef: "application/1", borrowerId: "b3", applicationId: "a1" }, NOW); assert.equal(converted.status, "converted"); assert.equal(converted.convertedApplicationId, "a1");
});

test("customer relationships, governed merge plans, and accessibility preferences preserve customer intent", () => {
  const state = baseState(); const relationship = registerCustomerRelationship({}, state, { relationshipId: "rel1", fromBorrowerId: "b1", toBorrowerId: "b2", relationshipType: "guarantor", liabilityType: "guarantee", evidenceRef: "relationship/1", ...approval }, NOW).relationship; assert.equal(relationship.status, "active"); const plan = createCustomerMergePlan({}, state, { mergePlanId: "merge1", survivorBorrowerId: "b1", duplicateBorrowerIds: ["b2"], matchEvidenceRefs: ["match/1"], conflictResolutions: { contact: "retain_survivor" }, migrationScope: ["applications", "consents", "documents"], rollbackRef: "rollback/1", ...approval }, NOW).plan; assert.equal(plan.status, "approved_not_executed");
  const preferences = recordCustomerPreferences({}, state, { borrowerId: "b1", preferredLanguage: "hi", communicationLanguages: ["hi", "en"], vulnerabilityFlags: ["senior_citizen"], accessibilityNeeds: ["large_text"], assistedJourney: true, doNotContactChannels: ["voice"], permittedContactWindows: ["10:00-16:00"], consentRef: "preferences/consent", recordedBy: "service-agent" }, NOW).preferences; assert.equal(preferences.preferredLanguage, "hi"); assert.equal(preferences.assistedJourney, true);
});

test("nominee and legal-heir succession remains manually restricted through independent approval", () => {
  const state = baseState(); const relationship = registerCustomerRelationship({}, state, { relationshipId: "nominee1", fromBorrowerId: "b1", toBorrowerId: "b2", relationshipType: "nominee", evidenceRef: "nomination/1", ...approval }, NOW).relationship; const caseState = { ...state, customerRelationships: { [relationship.relationshipId]: relationship } }; let succession = createSuccessionCase({}, caseState, { caseId: "succession1", borrowerId: "b1", claimantBorrowerId: "b2", relationshipId: "nominee1", deathCertificateRef: "death/1", identityEvidenceRefs: ["identity/1"], legalEvidenceRefs: ["legal/1"], affectedLoanAccountIds: ["loan1"], reportedBy: "service-agent" }, NOW).successionCase; assert.equal(succession.servicingRestriction, "manual_review_only"); succession = transitionSuccessionCase(succession, { action: "verify", actor: "service-agent", reason: "documents verified", evidenceRefs: ["verification/1"] }, NOW); assert.throws(() => transitionSuccessionCase(succession, { action: "approve", actor: "manager", reason: "approve", evidenceRefs: ["approval/1"], proposedBy: "manager", approvedBy: "manager", approvalRef: "same" }, NOW), /Independent/); succession = transitionSuccessionCase(succession, { action: "approve", actor: "manager", reason: "approve", evidenceRefs: ["approval/1"], proposedBy: "service-agent", approvedBy: "manager", approvalRef: "approval/2" }, NOW); assert.equal(succession.status, "approved");
});

test("customer 360 aggregates related-party exact exposure and lifecycle records", () => {
  const state = baseState(); const relationship = registerCustomerRelationship({}, state, { relationshipId: "household1", fromBorrowerId: "b1", toBorrowerId: "b2", relationshipType: "household", evidenceRef: "household/1", ...approval }, NOW).relationship; const view = buildCustomer360({ ...state, customerRelationships: { household1: relationship }, loanAccounts: { l1: { loanAccountId: "l1", borrowerId: "b1", status: "active", ledger: [{ eventDate: NOW.toISOString(), principalDebit: 1000 }] }, l2: { loanAccountId: "l2", borrowerId: "b2", status: "active", ledger: [{ eventDate: NOW.toISOString(), principalDebit: 500 }] } }, loanApplications: { a1: { applicationId: "a1", borrowerId: "b1" } }, complaints: {}, consentRecords: {}, documentVault: {}, successionCases: {} }, "b1", NOW); assert.equal(view.aggregateExposurePaise, "150000"); assert.equal(view.loanAccounts.length, 2); assert.equal(view.relatedBorrowers[0].borrowerId, "b2");
});

test("customer channel APIs persist preferences and expose customer 360", async (t) => {
  const dataDir = await mkdtemp(join(tmpdir(), "loanos-channel-")); const tenant = { tenantId: "tenant_channel", name: "Channel Bank", apiKey: "channel-key" }; const server = createLoanOsServer({ dataDir, bootstrapTenants: [tenant] }); await new Promise((resolve, reject) => server.listen(0, "127.0.0.1", (error) => error ? reject(error) : resolve())); t.after(async () => { await new Promise((resolve) => server.close(resolve)); await rm(dataDir, { recursive: true, force: true }); }); const base = `http://127.0.0.1:${server.address().port}`; const headers = { "content-type": "application/json", "x-api-key": tenant.apiKey };
  let response = await fetch(`${base}/t/tenant_channel/partners/`); assert.equal(response.status, 200); assert.match(await response.text(), /Every lead begins with consent/); response = await fetch(`${base}/t/tenant_channel/partners/manifest.webmanifest`); assert.equal(response.headers.get("content-type"), "application/manifest+json; charset=utf-8"); response = await fetch(`${base}/t/tenant_channel/partners/sw.js`); assert.equal(response.headers.get("cache-control"), "no-cache"); assert.match(await response.text(), /customer or lead data|isStaticShell/);
  response = await fetch(`${base}/borrowers`, { method: "POST", headers, body: JSON.stringify({ borrowerId: "b1", borrowerType: "individual", status: "active", fullName: "Asha", dateOfBirth: "1990-01-01", contact: { email: "asha@example.in" }, economicProfile: { occupation: "salaried", monthlyIncome: 50000 } }) }); assert.equal(response.status, 201, await response.clone().text()); response = await fetch(`${base}/customers/preferences`, { method: "POST", headers, body: JSON.stringify({ borrowerId: "b1", preferredLanguage: "hi", communicationLanguages: ["hi", "en"], vulnerabilityFlags: [], accessibilityNeeds: ["large_text"], assistedJourney: true, doNotContactChannels: [], permittedContactWindows: ["10:00-16:00"], consentRef: "consent/1" }) }); assert.equal(response.status, 201, await response.clone().text()); response = await fetch(`${base}/customers/b1/360`, { headers: { "x-api-key": tenant.apiKey } }); const view = await response.json(); assert.equal(view.preferences.preferredLanguage, "hi"); assert.equal(view.aggregateExposurePaise, "0");
  response = await fetch(`${base}/admin/users`, { method: "POST", headers, body: JSON.stringify({ email: "partner@channel.in", displayName: "Scoped Partner", password: "PartnerPass1!", mustChangePassword: false, adminRoles: ["operator"], channelScope: { mode: "partner", partnerIds: ["dsa1"] } }) }); assert.equal(response.status, 201, await response.clone().text()); response = await fetch(`${base}/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tenantId: tenant.tenantId, email: "partner@channel.in", password: "PartnerPass1!" }) }); assert.equal(response.status, 200, await response.clone().text()); const cookie = response.headers.get("set-cookie").split(";")[0]; response = await fetch(`${base}/channels/operations`, { headers: { cookie } }); const scoped = await response.json(); assert.equal(response.status, 200); assert.equal(scoped.scope.mode, "partner"); assert.deepEqual(scoped.customerPreferences, []); response = await fetch(`${base}/customers/b1/360`, { headers: { cookie } }); assert.equal(response.status, 403); assert.equal((await response.json()).error.code, "customer_scope_forbidden");
});

test("partner and branch user scopes fail closed and exclude customer master data", () => {
  const partnerUser = upsertTenantUser({}, { email: "agent@partner.in", password: "PartnerPass1!", adminRoles: ["operator"], channelScope: { mode: "partner", partnerIds: ["dsa1"] } }, NOW); assert.deepEqual(partnerUser.findings, []); assert.deepEqual(partnerUser.user.channelScope.partnerIds, ["dsa1"]);
  const invalid = upsertTenantUser({}, { email: "agent@invalid.in", password: "PartnerPass1!", adminRoles: ["operator"], channelScope: { mode: "partner", partnerIds: [] } }, NOW); assert.equal(invalid.findings[0].code, "user_channel_scope_invalid");
  const state = { ...baseState(), channelPartners: { dsa1: { ...partner(baseState()), operatingUnitIds: ["branch1"] }, dsa2: { ...partner(baseState()), partnerId: "dsa2", legalName: "Other DSA", operatingUnitIds: ["branch1"] } }, partnerCommissionPolicies: { c1: { policyId: "c1", partnerId: "dsa1" }, c2: { policyId: "c2", partnerId: "dsa2" } }, channelLeads: { l1: { leadId: "l1", partnerId: "dsa1", operatingUnitId: "branch1" }, l2: { leadId: "l2", partnerId: "dsa2", operatingUnitId: "branch1" } }, customerRelationships: { secret: { relationshipId: "secret" } }, customerMergePlans: {}, customerPreferences: { b1: { borrowerId: "b1" } }, successionCases: {} };
  const view = projectChannelOperations(state, partnerUser.user.channelScope); assert.deepEqual(view.channelLeads.map((item) => item.leadId), ["l1"]); assert.deepEqual(view.channelPartners.map((item) => item.partnerId), ["dsa1"]); assert.equal(view.customerRelationships.length, 0); assert.equal(view.customerPreferences.length, 0);
});

test("partner commission is exact, independently approved, reconciled, and clawback-window bound", () => {
  const base = baseState(); const channelPartner = partner(base); const policy = registerPartnerCommissionPolicy({}, { ...base, channelPartners: { dsa1: channelPartner } }, { policyId: "commission1", partnerId: "dsa1", programmeIds: ["programme1"], basis: "disbursed_amount_bps", rateBps: 125, maximumPayoutPaise: "500000", eligibleEvent: "disbursement", clawbackDays: 90, taxTreatmentRef: "tax/tds", ...approval }, NOW).policy; const lead = { leadId: "lead1", partnerId: "dsa1", programmeId: "programme1", status: "converted", convertedApplicationId: "a1", convertedBorrowerId: "b1" }; const state = { ...base, channelLeads: { lead1: lead }, partnerCommissionPolicies: { commission1: policy } };
  let assessment = assessPartnerCommission({}, state, { assessmentId: "ca1", leadId: "lead1", policyId: "commission1", eligibleEvent: "disbursement", eligibleEventRef: "disbursement/d1", eligibleAt: NOW.toISOString(), baseAmountPaise: "10000000", taxWithheldPaise: "12500", assessedBy: "finance-maker" }, NOW).assessment; assert.equal(assessment.grossCommissionPaise, "125000"); assert.equal(assessment.netPayablePaise, "112500"); assert.throws(() => transitionPartnerCommission(assessment, state, { action: "approve", actor: "finance-maker", approvalRef: "same", reason: "approve", evidenceRef: "approval/1" }, NOW), /Independent/); assessment = transitionPartnerCommission(assessment, state, { action: "approve", actor: "finance-checker", approvalRef: "approval/1", reason: "verified", evidenceRef: "workpaper/1" }, NOW); assessment = transitionPartnerCommission(assessment, state, { action: "settle", actor: "accounts-payable", reason: "paid", evidenceRef: "bank/1", paymentRef: "utr/1", reconciliationRef: "recon/1" }, NOW); assert.equal(assessment.status, "settled"); assert.equal(assessment.paymentRef, "utr/1"); assessment = transitionPartnerCommission(assessment, state, { action: "claw_back", actor: "finance-checker", reason: "loan cancelled", evidenceRef: "cancellation/1" }, new Date("2026-08-01T00:00:00.000Z")); assert.equal(assessment.status, "clawed_back");
});
