import test from "node:test"; import assert from "node:assert/strict";
import { acquireIntegrationJobLease, createIntegrationJob, emptyIntegrationWorkerState, failIntegrationJob, integrationPayloadChecksum, integrationWorkerHealth, replayDeadLetterJob, runIntegrationWorkerOnce } from "../packages/core/src/integration-worker-operations.js";
const NOW=new Date("2026-07-15T10:00:00Z");
function queued(state=emptyIntegrationWorkerState(),overrides={}){const payload=overrides.payload??{eventId:"e1"};return createIntegrationJob(state,{tenantId:"t1",jobId:overrides.jobId??"j1",type:overrides.type??"callback_dispatch",idempotencyKey:overrides.idempotencyKey??"i1",payload,payloadChecksumSha256:integrationPayloadChecksum(payload),maxAttempts:overrides.maxAttempts??2},NOW).state;}
test("jobs persist exact checksums and tenant-local idempotency",()=>{const state=queued();const same=createIntegrationJob(state,{tenantId:"t1",jobId:"j2",type:"callback_dispatch",idempotencyKey:"i1",payload:{eventId:"e1"},payloadChecksumSha256:integrationPayloadChecksum({eventId:"e1"})},NOW);assert.equal(same.idempotent,true);assert.throws(()=>createIntegrationJob(state,{tenantId:"t1",jobId:"j2",type:"callback_dispatch",idempotencyKey:"i1",payload:{eventId:"different"},payloadChecksumSha256:integrationPayloadChecksum({eventId:"different"})},NOW),(e)=>e.code==="integration_job_idempotency_conflict");});
test("leases use fencing and reject stale, expired, and cross-tenant mutation",()=>{const leased=acquireIntegrationJobLease(queued(),{tenantId:"t1",workerId:"w1",leaseMs:1000},NOW);assert.equal(leased.job.lease.fence,1);assert.throws(()=>failIntegrationJob(leased.state,{tenantId:"t1",jobId:"j1",workerId:"w2",fence:1,errorCode:"x",errorEvidenceRef:"e"},NOW),(e)=>e.code==="integration_lease_fenced");assert.throws(()=>failIntegrationJob(leased.state,{tenantId:"t1",jobId:"j1",workerId:"w1",fence:1,errorCode:"x",errorEvidenceRef:"e"},new Date("2026-07-15T10:00:02Z")),(e)=>e.code==="integration_lease_expired");});
test("bounded retry reaches DLQ and replay requires four eyes",()=>{let state=queued(emptyIntegrationWorkerState(),{maxAttempts:1});const lease=acquireIntegrationJobLease(state,{tenantId:"t1",workerId:"w1"},NOW);const failed=failIntegrationJob(lease.state,{tenantId:"t1",jobId:"j1",workerId:"w1",fence:1,errorCode:"timeout",errorEvidenceRef:"evidence://timeout"},NOW);assert.equal(failed.job.status,"dead_letter");assert.throws(()=>replayDeadLetterJob(failed.state,{tenantId:"t1",jobId:"j1",proposedBy:"same",approvedBy:"same",approvalRef:"a",reason:"provider recovered"},NOW),(e)=>e.code==="integration_replay_four_eyes_required");const replay=replayDeadLetterJob(failed.state,{tenantId:"t1",jobId:"j1",proposedBy:"operator",approvedBy:"checker",approvalRef:"approval://replay",reason:"provider recovered"},NOW);assert.equal(replay.job.status,"queued");assert.equal(replay.job.replayHistory.length,1);});
test("runOnce composes callback and signed-file handlers with revision CAS persistence",async()=>{let initial=queued();initial=queued(initial,{jobId:"j2",idempotencyKey:"i2",type:"signed_file_poll",payload:{file:"ack.zip"}});let persisted=structuredClone(initial);const store={load:async()=>structuredClone(persisted),save:async(next,{expectedRevision})=>{assert.equal(persisted.revision,expectedRevision);persisted=structuredClone(next);}};const seen=[];const result=await runIntegrationWorkerOnce({tenantId:"t1",workerId:"worker-1",store,handlers:{callback_dispatch:async(job)=>{seen.push(job.type);return{evidenceRef:"callback://sent"};},signed_file_poll:async(job)=>{seen.push(job.type);return{evidenceRef:"file://verified"};}},now:NOW});assert.equal(result.processedCount,2);assert.deepEqual(Object.values(persisted.jobs).map(j=>j.status),["completed","completed"]);assert.equal(integrationWorkerHealth(persisted,{tenantId:"t1"},NOW).status,"healthy");});
test("runOnce fails closed into retry/DLQ and rejects cross-tenant persisted state",async()=>{let persisted=queued(emptyIntegrationWorkerState(),{maxAttempts:1});const store={load:async()=>structuredClone(persisted),save:async(next,{expectedRevision})=>{assert.equal(persisted.revision,expectedRevision);persisted=structuredClone(next);}};await runIntegrationWorkerOnce({tenantId:"t1",workerId:"w",store,handlers:{callback_dispatch:async()=>{throw Object.assign(new Error("bad signature"),{code:"signature_invalid",evidenceRef:"evidence://bad"});},signed_file_poll:async()=>({evidenceRef:"x"})},now:NOW,maxJobs:1});assert.equal(persisted.jobs.j1.status,"dead_letter");const badStore={load:async()=>({revision:0,jobs:{x:{tenantId:"t2"}}}),save:async()=>{}};await assert.rejects(()=>runIntegrationWorkerOnce({tenantId:"t1",workerId:"w",store:badStore,handlers:{callback_dispatch:async()=>({evidenceRef:"x"}),signed_file_poll:async()=>({evidenceRef:"x"})},now:NOW}),(e)=>e.code==="integration_store_tenant_mismatch");});
