import test from "node:test";
import assert from "node:assert/strict";
import { approveProductAddon, approveProfitabilityParameters, approveRiskPricingMatrix, approveTenantPlan, authorizePlanUsage, createTenantCommunication, diffProductVersions, importTenantPortablePackage, promoteEnvironmentConfiguration } from "@loanos/core/platform/platform-product-completion.js";
const NOW = new Date("2026-07-15T10:00:00Z"); const approval = { tenantId: "t1", proposedBy: "maker", approvedBy: "checker", approvalRef: "approval://1" };

test("tenant plans fail closed on entitlement, exact limits and tenant scope", () => { const plan = approveTenantPlan({ ...approval, planId: "pro", version: "1", entitlements: ["origination"], limits: { users: 2 }, termsRef: "terms://1" }, [], NOW); assert.equal(authorizePlanUsage(plan, { tenantId: "t1", entitlement: "origination", limitKey: "users", currentUsage: 1 }).decision, "allow"); assert.throws(() => authorizePlanUsage(plan, { tenantId: "t1", entitlement: "origination", limitKey: "users", currentUsage: 2 }), /limit/); assert.throws(() => authorizePlanUsage(plan, { tenantId: "t2", entitlement: "origination" }), (e) => e.code === "platform_product_tenant_mismatch"); });
test("configuration promotion and portability require ordered, reconciled, checksum-bound approval", () => { const promoted = promoteEnvironmentConfiguration({ ...approval, configurationId: "cfg", version: "1", sourceEnvironment: "staging", targetEnvironment: "production", payloadChecksumSha256: "a".repeat(64), sourceEvidenceRef: "git://1", testEvidenceRef: "test://1" }, [], NOW); assert.equal(promoted.status, "promoted"); assert.throws(() => promoteEnvironmentConfiguration({ ...promoted, proposedBy: "m", approvedBy: "c", sourceEnvironment: "test", targetEnvironment: "production" }, [], NOW), /exactly one/); const imported = importTenantPortablePackage({ ...approval, importId: "i1", packageId: "p1", schemaVersion: "1", archiveRef: "vault://p1", archiveChecksumSha256: "a".repeat(64), manifestChecksumSha256: "b".repeat(64), exportTenantId: "t1", checksumVerified: true, schemaCompatible: true, rowCountsReconciled: true, validationEvidenceRef: "validation://1" }, [], NOW); assert.equal(imported.status, "imported"); assert.throws(() => importTenantPortablePackage({ ...approval, importId: "i2", packageId: "p2", schemaVersion: "1", archiveRef: "x", archiveChecksumSha256: "a".repeat(64), manifestChecksumSha256: "b".repeat(64), exportTenantId: "t1", checksumVerified: true, schemaCompatible: true, rowCountsReconciled: false, validationEvidenceRef: "x" }, [], NOW), /validation/); });
test("tenant communications retain independently approved SLA, release, maintenance and incident detail", () => { const item = createTenantCommunication({ ...approval, communicationId: "c1", type: "maintenance", subject: "Scheduled database maintenance", messageRef: "message://1", audience: "tenant-admins", impactRef: "impact://1", startsAt: "2026-07-20T10:00:00Z", endsAt: "2026-07-20T11:00:00Z" }, [], NOW); assert.equal(item.type, "maintenance"); assert.throws(() => createTenantCommunication({ ...approval, communicationId: "c2", type: "incident", subject: "Service incident", messageRef: "m", audience: "admins", startsAt: "2026-07-20T10:00:00Z" }, [], NOW), /Impact/); });
test("risk pricing uses exact paise and bps with non-overlapping score bands", () => { const matrix = approveRiskPricingMatrix({ ...approval, matrixId: "risk", version: "1", policyRef: "policy://1", bands: [{ riskBand: "low", minScore: 750, maxScore: 900, annualRateBps: "1200", processingFeePaise: "10000" }, { riskBand: "medium", minScore: 600, maxScore: 749, annualRateBps: "1600", processingFeePaise: "15000" }] }, [], NOW); assert.equal(matrix.bands[0].annualRateBps, "1200"); assert.throws(() => approveRiskPricingMatrix({ ...approval, matrixId: "bad", version: "1", policyRef: "p", bands: [{ riskBand: "a", minScore: 1, maxScore: 5, annualRateBps: "1.5", processingFeePaise: "0" }] }, [], NOW), /exact/); });
test("product version impact is checksum-bound and identifies migrations", () => { const from = { tenantId: "t1", productId: "pl", version: "1", definition: { tenure: 12, rateBps: "1200" } }; const to = { ...from, version: "2", definition: { tenure: 24, rateBps: "1300" } }; const diff = diffProductVersions(from, to, { tenantId: "t1", assessmentId: "d1", impactedActiveAccountCount: 3, assessedBy: "maker", approvedBy: "checker", approvalRef: "approval://diff" }, NOW); assert.equal(diff.changes.length, 2); assert.equal(diff.migrationRequired, true); });
test("add-ons require opt-in and profitability parameters retain exact RAROC inputs", () => { const addon = approveProductAddon({ ...approval, addonId: "ins", version: "1", addonType: "insurance", providerRef: "provider://1", disclosureRef: "disclosure://1", consentTextRef: "consent://1", premiumPaise: "50000", commissionBps: "100", optional: true, preselected: false }, [], NOW); assert.equal(addon.optional, true); assert.throws(() => approveProductAddon({ ...addon, proposedBy: "m", approvedBy: "c", preselected: true }, [], NOW), /optional/); const params = approveProfitabilityParameters({ ...approval, parameterSetId: "raroc", version: "1", methodologyRef: "method://1", costOfFundsBps: "800", operatingCostPaise: "100000", expectedLossBps: "200", capitalAllocationBps: "1000", targetRarocBps: "1800" }, [], NOW); assert.equal(params.targetRarocBps, "1800"); });
