import test from "node:test";
import assert from "node:assert/strict";
import { createProviderSimulator, verifySimulatedProviderCallback } from "../packages/core/src/provider-simulator.js";

const config = { tenantId: "tenant-a", seed: "suite-seed", callbackSecret: "callback-secret", startAt: "2026-07-15T10:00:00.000Z", scenarios: {
  success: { outcome: "success", response: { score: 780 }, callbacks: [{ eventType: "report.ready", delayMs: 1000 }] },
  duplicate: { outcome: "success", duplicates: true, callbacks: [{ eventType: "payment.settled", delayMs: 0 }] },
  out_of_order: { outcome: "success", outOfOrder: true, callbacks: [{ eventType: "mandate.created", sequence: 1 }, { eventType: "mandate.activated", sequence: 2 }] },
  tamper: { outcome: "success", tamper: true }, timeout: { outcome: "timeout" }, rate_limit: { outcome: "rate_limit", retryAfterMs: 30000 }, failure: { outcome: "failure", responseCode: "SCHEMA_INVALID" }
} };

test("seed, clock and request payload produce deterministic IDs and journal hashes", () => { const one = createProviderSimulator(config), two = createProviderSimulator(config); const input = { tenantId: "tenant-a", provider: "bureau", operation: "query", idempotencyKey: "q1", scenario: "success", payload: { pan: "ABCDE1234F" } }; assert.deepEqual(one.submit(input), two.submit(input)); assert.deepEqual(one.requestJournal(), two.requestJournal()); assert.equal(one.pendingCallbacks()[0].deliverAt, "2026-07-15T10:00:01.000Z"); assert.equal(one.drainCallbacks().length, 0); one.advance(1000); assert.equal(one.drainCallbacks().length, 1); });
test("idempotency returns the original response and journals duplicate attempts", () => { const sim = createProviderSimulator(config); const input = { tenantId: "tenant-a", provider: "aa", operation: "fetch", idempotencyKey: "fetch-1", scenario: "success", payload: {} }; const first = sim.submit(input), second = sim.submit(input); assert.deepEqual(second, first); assert.equal(sim.requestJournal().length, 2); assert.equal(sim.requestJournal()[1].duplicate, true); assert.equal(sim.pendingCallbacks().length, 1); });
test("scheduled callbacks can be duplicated, delivered out of order and signature verified", () => { const duplicate = createProviderSimulator(config); duplicate.submit({ tenantId: "tenant-a", provider: "payment_rail", operation: "collect", idempotencyKey: "p1", scenario: "duplicate", payload: {} }); const callbacks = duplicate.drainCallbacks(); assert.equal(callbacks.length, 2); assert.equal(callbacks[1].duplicate, true); assert.equal(callbacks.every((item) => duplicate.verify(item) && verifySimulatedProviderCallback(item, "callback-secret")), true); const unordered = createProviderSimulator(config); unordered.submit({ tenantId: "tenant-a", provider: "payment_rail", operation: "mandate", idempotencyKey: "m1", scenario: "out_of_order", payload: {} }); assert.deepEqual(unordered.drainCallbacks().map((item) => item.payload.eventType), ["mandate.activated", "mandate.created"]); });
test("tamper, timeout, rate-limit and provider failure scenarios fail safely", () => { const sim = createProviderSimulator(config); sim.submit({ tenantId: "tenant-a", provider: "esign", operation: "sign", idempotencyKey: "s1", scenario: "tamper", payload: {} }); assert.equal(sim.verify(sim.drainCallbacks()[0]), false); assert.throws(() => sim.submit({ tenantId: "tenant-a", provider: "vcip", operation: "analyze", idempotencyKey: "v1", scenario: "timeout", payload: {} }), (error) => error.code === "provider_simulator_timeout"); assert.throws(() => sim.submit({ tenantId: "tenant-a", provider: "sms", operation: "send", idempotencyKey: "c1", scenario: "rate_limit", payload: {} }), (error) => error.code === "provider_simulator_rate_limited" && error.retryAfterMs === 30000); const failed = sim.submit({ tenantId: "tenant-a", provider: "ckycrr", operation: "submit", idempotencyKey: "k1", scenario: "failure", payload: {} }); assert.equal(failed.success, false); assert.equal(failed.responseCode, "SCHEMA_INVALID"); });
test("tenant mismatch and unknown scenarios fail closed", () => { const sim = createProviderSimulator(config); assert.throws(() => sim.submit({ tenantId: "tenant-b", provider: "bureau", operation: "query", idempotencyKey: "q", scenario: "success" }), (error) => error.code === "provider_simulator_tenant_mismatch"); assert.throws(() => sim.submit({ tenantId: "tenant-a", provider: "bureau", operation: "query", idempotencyKey: "q", scenario: "missing" }), (error) => error.code === "provider_simulator_scenario_missing"); });
